/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication and tenant administration. The determination surface named in `ZTAX-INT-001` — quotes, transaction commit, adjust, refund, decisions, replay, classifications, obligations, batches and jobs — is not here yet and is added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  This version of the surface carries no fiscal amounts. The rule is stated here because it governs every addition to it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AuditRecord
 */
@JsonPropertyOrder({
  AuditRecord.JSON_PROPERTY_ID,
  AuditRecord.JSON_PROPERTY_ACTOR_USER_ID,
  AuditRecord.JSON_PROPERTY_ACTION,
  AuditRecord.JSON_PROPERTY_SUBJECT_TYPE,
  AuditRecord.JSON_PROPERTY_SUBJECT_ID,
  AuditRecord.JSON_PROPERTY_DETAIL,
  AuditRecord.JSON_PROPERTY_RECORDED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AuditRecord {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_ACTOR_USER_ID = "actorUserId";
  @jakarta.annotation.Nullable
  private String actorUserId;

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nonnull
  private String action;

  public static final String JSON_PROPERTY_SUBJECT_TYPE = "subjectType";
  @jakarta.annotation.Nonnull
  private String subjectType;

  public static final String JSON_PROPERTY_SUBJECT_ID = "subjectId";
  @jakarta.annotation.Nonnull
  private String subjectId;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  @jakarta.annotation.Nonnull
  private String detail;

  public static final String JSON_PROPERTY_RECORDED_AT = "recordedAt";
  @jakarta.annotation.Nonnull
  private String recordedAt;

  public AuditRecord() { 
  }

  public AuditRecord id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * An audit record identifier (ADR-0012).
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public AuditRecord actorUserId(@jakarta.annotation.Nullable String actorUserId) {
    this.actorUserId = actorUserId;
    return this;
  }

  /**
   * Absent where the action had no human actor — a bootstrap at startup, or a scheduled sweep. Absent rather than a placeholder identifier, because \&quot;the system did this\&quot; and \&quot;some user did this\&quot; are different facts. 
   * @return actorUserId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTOR_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getActorUserId() {
    return actorUserId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTOR_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActorUserId(@jakarta.annotation.Nullable String actorUserId) {
    this.actorUserId = actorUserId;
  }


  public AuditRecord action(@jakarta.annotation.Nonnull String action) {
    this.action = action;
    return this;
  }

  /**
   * A dotted action name from a closed vocabulary.
   * @return action
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@jakarta.annotation.Nonnull String action) {
    this.action = action;
  }


  public AuditRecord subjectType(@jakarta.annotation.Nonnull String subjectType) {
    this.subjectType = subjectType;
    return this;
  }

  /**
   * Get subjectType
   * @return subjectType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubjectType() {
    return subjectType;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubjectType(@jakarta.annotation.Nonnull String subjectType) {
    this.subjectType = subjectType;
  }


  public AuditRecord subjectId(@jakarta.annotation.Nonnull String subjectId) {
    this.subjectId = subjectId;
    return this;
  }

  /**
   * Get subjectId
   * @return subjectId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubjectId() {
    return subjectId;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubjectId(@jakarta.annotation.Nonnull String subjectId) {
    this.subjectId = subjectId;
  }


  public AuditRecord detail(@jakarta.annotation.Nonnull String detail) {
    this.detail = detail;
    return this;
  }

  /**
   * A canonical JSON document, as a string. It is the exact bytes that were recorded and digested, so it is passed through rather than re-encoded (ADR-0011 §2.7). 
   * @return detail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetail(@jakarta.annotation.Nonnull String detail) {
    this.detail = detail;
  }


  public AuditRecord recordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return recordedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecordedAt() {
    return recordedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
  }


  /**
   * Return true if this AuditRecord object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditRecord auditRecord = (AuditRecord) o;
    return Objects.equals(this.id, auditRecord.id) &&
        Objects.equals(this.actorUserId, auditRecord.actorUserId) &&
        Objects.equals(this.action, auditRecord.action) &&
        Objects.equals(this.subjectType, auditRecord.subjectType) &&
        Objects.equals(this.subjectId, auditRecord.subjectId) &&
        Objects.equals(this.detail, auditRecord.detail) &&
        Objects.equals(this.recordedAt, auditRecord.recordedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, actorUserId, action, subjectType, subjectId, detail, recordedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditRecord {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    actorUserId: ").append(toIndentedString(actorUserId)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    recordedAt: ").append(toIndentedString(recordedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

