/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.AiProvenance;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * An advisory mapping proposal. &#x60;authoritative&#x60; is always false; a person confirms it or it is nothing.
 */
@JsonPropertyOrder({
  ClassificationProposal.JSON_PROPERTY_ID,
  ClassificationProposal.JSON_PROPERTY_SUBJECT_REF,
  ClassificationProposal.JSON_PROPERTY_PROPOSED_CODE,
  ClassificationProposal.JSON_PROPERTY_CONFIDENCE,
  ClassificationProposal.JSON_PROPERTY_AUTHORITATIVE,
  ClassificationProposal.JSON_PROPERTY_PROVENANCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ClassificationProposal {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_SUBJECT_REF = "subjectRef";
  @jakarta.annotation.Nonnull
  private String subjectRef;

  public static final String JSON_PROPERTY_PROPOSED_CODE = "proposedCode";
  @jakarta.annotation.Nonnull
  private String proposedCode;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @jakarta.annotation.Nullable
  private String confidence;

  /**
   * Gets or Sets authoritative
   */
  public enum AuthoritativeEnum {
    FALSE(Boolean.valueOf("false")),
    
    UNKNOWN_DEFAULT_OPEN_API(Boolean.valueOf("11184809"));

    private Boolean value;

    AuthoritativeEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthoritativeEnum fromValue(Boolean value) {
      for (AuthoritativeEnum b : AuthoritativeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_AUTHORITATIVE = "authoritative";
  @jakarta.annotation.Nonnull
  private AuthoritativeEnum authoritative;

  public static final String JSON_PROPERTY_PROVENANCE = "provenance";
  @jakarta.annotation.Nonnull
  private AiProvenance provenance;

  public ClassificationProposal() { 
  }

  public ClassificationProposal id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public ClassificationProposal subjectRef(@jakarta.annotation.Nonnull String subjectRef) {
    this.subjectRef = subjectRef;
    return this;
  }

  /**
   * Get subjectRef
   * @return subjectRef
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubjectRef() {
    return subjectRef;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubjectRef(@jakarta.annotation.Nonnull String subjectRef) {
    this.subjectRef = subjectRef;
  }


  public ClassificationProposal proposedCode(@jakarta.annotation.Nonnull String proposedCode) {
    this.proposedCode = proposedCode;
    return this;
  }

  /**
   * An existing ontology node, &#x60;ontology:...&#x60;.
   * @return proposedCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROPOSED_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProposedCode() {
    return proposedCode;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPOSED_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProposedCode(@jakarta.annotation.Nonnull String proposedCode) {
    this.proposedCode = proposedCode;
  }


  public ClassificationProposal confidence(@jakarta.annotation.Nullable String confidence) {
    this.confidence = confidence;
    return this;
  }

  /**
   * The model&#39;s own score as a canonical decimal in [0, 1]. Never a threshold that makes the proposal authoritative.
   * @return confidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConfidence() {
    return confidence;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidence(@jakarta.annotation.Nullable String confidence) {
    this.confidence = confidence;
  }


  public ClassificationProposal authoritative(@jakarta.annotation.Nonnull AuthoritativeEnum authoritative) {
    this.authoritative = authoritative;
    return this;
  }

  /**
   * Get authoritative
   * @return authoritative
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORITATIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthoritativeEnum getAuthoritative() {
    return authoritative;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORITATIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthoritative(@jakarta.annotation.Nonnull AuthoritativeEnum authoritative) {
    this.authoritative = authoritative;
  }


  public ClassificationProposal provenance(@jakarta.annotation.Nonnull AiProvenance provenance) {
    this.provenance = provenance;
    return this;
  }

  /**
   * Get provenance
   * @return provenance
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVENANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AiProvenance getProvenance() {
    return provenance;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVENANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvenance(@jakarta.annotation.Nonnull AiProvenance provenance) {
    this.provenance = provenance;
  }


  /**
   * Return true if this ClassificationProposal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationProposal classificationProposal = (ClassificationProposal) o;
    return Objects.equals(this.id, classificationProposal.id) &&
        Objects.equals(this.subjectRef, classificationProposal.subjectRef) &&
        Objects.equals(this.proposedCode, classificationProposal.proposedCode) &&
        Objects.equals(this.confidence, classificationProposal.confidence) &&
        Objects.equals(this.authoritative, classificationProposal.authoritative) &&
        Objects.equals(this.provenance, classificationProposal.provenance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subjectRef, proposedCode, confidence, authoritative, provenance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationProposal {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subjectRef: ").append(toIndentedString(subjectRef)).append("\n");
    sb.append("    proposedCode: ").append(toIndentedString(proposedCode)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    authoritative: ").append(toIndentedString(authoritative)).append("\n");
    sb.append("    provenance: ").append(toIndentedString(provenance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

