/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication and tenant administration. The determination surface named in `ZTAX-INT-001` — quotes, transaction commit, adjust, refund, decisions, replay, classifications, obligations, batches and jobs — is not here yet and is added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  This version of the surface carries no fiscal amounts. The rule is stated here because it governs every addition to it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * The rule bundle this cell is running. Absent where no bundle is loaded.  The digest is here because it is what a replay names: quoting the bundle identifier alone would not distinguish two builds of one pack, and the difference between them is a difference in law. 
 */
@JsonPropertyOrder({
  ContentCapability.JSON_PROPERTY_BUNDLE_ID,
  ContentCapability.JSON_PROPERTY_DIGEST,
  ContentCapability.JSON_PROPERTY_IR_VERSION,
  ContentCapability.JSON_PROPERTY_NODE_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ContentCapability {
  public static final String JSON_PROPERTY_BUNDLE_ID = "bundleId";
  @jakarta.annotation.Nonnull
  private String bundleId;

  public static final String JSON_PROPERTY_DIGEST = "digest";
  @jakarta.annotation.Nonnull
  private String digest;

  public static final String JSON_PROPERTY_IR_VERSION = "irVersion";
  @jakarta.annotation.Nonnull
  private Integer irVersion;

  public static final String JSON_PROPERTY_NODE_COUNT = "nodeCount";
  @jakarta.annotation.Nonnull
  private Integer nodeCount;

  public ContentCapability() { 
  }

  public ContentCapability bundleId(@jakarta.annotation.Nonnull String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

  /**
   * Get bundleId
   * @return bundleId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBundleId() {
    return bundleId;
  }


  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBundleId(@jakarta.annotation.Nonnull String bundleId) {
    this.bundleId = bundleId;
  }


  public ContentCapability digest(@jakarta.annotation.Nonnull String digest) {
    this.digest = digest;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return digest
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDigest() {
    return digest;
  }


  @JsonProperty(value = JSON_PROPERTY_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDigest(@jakarta.annotation.Nonnull String digest) {
    this.digest = digest;
  }


  public ContentCapability irVersion(@jakarta.annotation.Nonnull Integer irVersion) {
    this.irVersion = irVersion;
    return this;
  }

  /**
   * The rule-IR instruction-set version the bundle was compiled for. A runtime that cannot execute a bundle refuses to load it and stays on the previous one rather than degrading (ADR-0005 §2.8). 
   * @return irVersion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IR_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getIrVersion() {
    return irVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_IR_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIrVersion(@jakarta.annotation.Nonnull Integer irVersion) {
    this.irVersion = irVersion;
  }


  public ContentCapability nodeCount(@jakarta.annotation.Nonnull Integer nodeCount) {
    this.nodeCount = nodeCount;
    return this;
  }

  /**
   * The size of the rule graph, for telemetry.
   * @return nodeCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NODE_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getNodeCount() {
    return nodeCount;
  }


  @JsonProperty(value = JSON_PROPERTY_NODE_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNodeCount(@jakarta.annotation.Nonnull Integer nodeCount) {
    this.nodeCount = nodeCount;
  }


  /**
   * Return true if this ContentCapability object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentCapability contentCapability = (ContentCapability) o;
    return Objects.equals(this.bundleId, contentCapability.bundleId) &&
        Objects.equals(this.digest, contentCapability.digest) &&
        Objects.equals(this.irVersion, contentCapability.irVersion) &&
        Objects.equals(this.nodeCount, contentCapability.nodeCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleId, digest, irVersion, nodeCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentCapability {\n");
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    irVersion: ").append(toIndentedString(irVersion)).append("\n");
    sb.append("    nodeCount: ").append(toIndentedString(nodeCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

