/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.AuthorizationEvent;
import com.zoikotax.sdk.model.AuthorizationPermission;
import com.zoikotax.sdk.model.AuthorizationType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CustomerAuthorization
 */
@JsonPropertyOrder({
  CustomerAuthorization.JSON_PROPERTY_ID,
  CustomerAuthorization.JSON_PROPERTY_LEGAL_ENTITY_ID,
  CustomerAuthorization.JSON_PROPERTY_COUNTRY,
  CustomerAuthorization.JSON_PROPERTY_AUTHORITY,
  CustomerAuthorization.JSON_PROPERTY_TYPE,
  CustomerAuthorization.JSON_PROPERTY_PERMISSIONS,
  CustomerAuthorization.JSON_PROPERTY_MATTERS,
  CustomerAuthorization.JSON_PROPERTY_PERIOD_FROM,
  CustomerAuthorization.JSON_PROPERTY_PERIOD_TO,
  CustomerAuthorization.JSON_PROPERTY_REPRESENTATIVE,
  CustomerAuthorization.JSON_PROPERTY_EFFECTIVE_FROM,
  CustomerAuthorization.JSON_PROPERTY_EXPIRES_AT,
  CustomerAuthorization.JSON_PROPERTY_EVIDENCE,
  CustomerAuthorization.JSON_PROPERTY_CREDENTIAL_REF,
  CustomerAuthorization.JSON_PROPERTY_SUPERSEDES,
  CustomerAuthorization.JSON_PROPERTY_STATUS,
  CustomerAuthorization.JSON_PROPERTY_IN_FORCE,
  CustomerAuthorization.JSON_PROPERTY_RECORDED_AT,
  CustomerAuthorization.JSON_PROPERTY_RECORDED_BY,
  CustomerAuthorization.JSON_PROPERTY_HISTORY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CustomerAuthorization {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_ID = "legalEntityId";
  @jakarta.annotation.Nonnull
  private UUID legalEntityId;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nonnull
  private String country;

  public static final String JSON_PROPERTY_AUTHORITY = "authority";
  @jakarta.annotation.Nonnull
  private String authority;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private AuthorizationType type;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nonnull
  private List<AuthorizationPermission> permissions;

  public static final String JSON_PROPERTY_MATTERS = "matters";
  @jakarta.annotation.Nonnull
  private List<String> matters;

  public static final String JSON_PROPERTY_PERIOD_FROM = "periodFrom";
  @jakarta.annotation.Nullable
  private String periodFrom;

  public static final String JSON_PROPERTY_PERIOD_TO = "periodTo";
  @jakarta.annotation.Nullable
  private String periodTo;

  public static final String JSON_PROPERTY_REPRESENTATIVE = "representative";
  @jakarta.annotation.Nullable
  private String representative;

  public static final String JSON_PROPERTY_EFFECTIVE_FROM = "effectiveFrom";
  @jakarta.annotation.Nonnull
  private String effectiveFrom;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nullable
  private String expiresAt;

  public static final String JSON_PROPERTY_EVIDENCE = "evidence";
  @jakarta.annotation.Nonnull
  private List<String> evidence;

  public static final String JSON_PROPERTY_CREDENTIAL_REF = "credentialRef";
  @jakarta.annotation.Nullable
  private String credentialRef;

  public static final String JSON_PROPERTY_SUPERSEDES = "supersedes";
  @jakarta.annotation.Nullable
  private UUID supersedes;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("ACTIVE")),
    
    REVOKED(String.valueOf("REVOKED")),
    
    SUPERSEDED(String.valueOf("SUPERSEDED")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_IN_FORCE = "inForce";
  @jakarta.annotation.Nonnull
  private Boolean inForce;

  public static final String JSON_PROPERTY_RECORDED_AT = "recordedAt";
  @jakarta.annotation.Nonnull
  private String recordedAt;

  public static final String JSON_PROPERTY_RECORDED_BY = "recordedBy";
  @jakarta.annotation.Nonnull
  private UUID recordedBy;

  public static final String JSON_PROPERTY_HISTORY = "history";
  @jakarta.annotation.Nonnull
  private List<AuthorizationEvent> history;

  public CustomerAuthorization() { 
  }

  public CustomerAuthorization id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public CustomerAuthorization legalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
    return this;
  }

  /**
   * A legal entity within the tenant (ZTAX-OBL-REQ-0018). A UUID in lowercase canonical form.
   * @return legalEntityId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getLegalEntityId() {
    return legalEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
  }


  public CustomerAuthorization country(@jakarta.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2.
   * @return country
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountry(@jakarta.annotation.Nonnull String country) {
    this.country = country;
  }


  public CustomerAuthorization authority(@jakarta.annotation.Nonnull String authority) {
    this.authority = authority;
    return this;
  }

  /**
   * An authority within a country, as the matrix names it.
   * @return authority
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAuthority() {
    return authority;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthority(@jakarta.annotation.Nonnull String authority) {
    this.authority = authority;
  }


  public CustomerAuthorization type(@jakarta.annotation.Nonnull AuthorizationType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthorizationType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull AuthorizationType type) {
    this.type = type;
  }


  public CustomerAuthorization permissions(@jakarta.annotation.Nonnull List<AuthorizationPermission> permissions) {
    this.permissions = permissions;
    return this;
  }

  public CustomerAuthorization addPermissionsItem(AuthorizationPermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<AuthorizationPermission> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissions(@jakarta.annotation.Nonnull List<AuthorizationPermission> permissions) {
    this.permissions = permissions;
  }


  public CustomerAuthorization matters(@jakarta.annotation.Nonnull List<String> matters) {
    this.matters = matters;
    return this;
  }

  public CustomerAuthorization addMattersItem(String mattersItem) {
    if (this.matters == null) {
      this.matters = new ArrayList<>();
    }
    this.matters.add(mattersItem);
    return this;
  }

  /**
   * Get matters
   * @return matters
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MATTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getMatters() {
    return matters;
  }


  @JsonProperty(value = JSON_PROPERTY_MATTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMatters(@jakarta.annotation.Nonnull List<String> matters) {
    this.matters = matters;
  }


  public CustomerAuthorization periodFrom(@jakarta.annotation.Nullable String periodFrom) {
    this.periodFrom = periodFrom;
    return this;
  }

  /**
   * A subledger legal period, a month.
   * @return periodFrom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIOD_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPeriodFrom() {
    return periodFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodFrom(@jakarta.annotation.Nullable String periodFrom) {
    this.periodFrom = periodFrom;
  }


  public CustomerAuthorization periodTo(@jakarta.annotation.Nullable String periodTo) {
    this.periodTo = periodTo;
    return this;
  }

  /**
   * A subledger legal period, a month.
   * @return periodTo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIOD_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPeriodTo() {
    return periodTo;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodTo(@jakarta.annotation.Nullable String periodTo) {
    this.periodTo = periodTo;
  }


  public CustomerAuthorization representative(@jakarta.annotation.Nullable String representative) {
    this.representative = representative;
    return this;
  }

  /**
   * The individual or entity acting under the grant.
   * @return representative
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPRESENTATIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRepresentative() {
    return representative;
  }


  @JsonProperty(value = JSON_PROPERTY_REPRESENTATIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepresentative(@jakarta.annotation.Nullable String representative) {
    this.representative = representative;
  }


  public CustomerAuthorization effectiveFrom(@jakarta.annotation.Nonnull String effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return effectiveFrom
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEffectiveFrom() {
    return effectiveFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEffectiveFrom(@jakarta.annotation.Nonnull String effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public CustomerAuthorization expiresAt(@jakarta.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public CustomerAuthorization evidence(@jakarta.annotation.Nonnull List<String> evidence) {
    this.evidence = evidence;
    return this;
  }

  public CustomerAuthorization addEvidenceItem(String evidenceItem) {
    if (this.evidence == null) {
      this.evidence = new ArrayList<>();
    }
    this.evidence.add(evidenceItem);
    return this;
  }

  /**
   * Get evidence
   * @return evidence
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getEvidence() {
    return evidence;
  }


  @JsonProperty(value = JSON_PROPERTY_EVIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidence(@jakarta.annotation.Nonnull List<String> evidence) {
    this.evidence = evidence;
  }


  public CustomerAuthorization credentialRef(@jakarta.annotation.Nullable String credentialRef) {
    this.credentialRef = credentialRef;
    return this;
  }

  /**
   * Where the authority credential is held in the secrets vault. Never the credential.
   * @return credentialRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCredentialRef() {
    return credentialRef;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentialRef(@jakarta.annotation.Nullable String credentialRef) {
    this.credentialRef = credentialRef;
  }


  public CustomerAuthorization supersedes(@jakarta.annotation.Nullable UUID supersedes) {
    this.supersedes = supersedes;
    return this;
  }

  /**
   * Get supersedes
   * @return supersedes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPERSEDES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getSupersedes() {
    return supersedes;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPERSEDES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupersedes(@jakarta.annotation.Nullable UUID supersedes) {
    this.supersedes = supersedes;
  }


  public CustomerAuthorization status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public CustomerAuthorization inForce(@jakarta.annotation.Nonnull Boolean inForce) {
    this.inForce = inForce;
    return this;
  }

  /**
   * Active, effective and not expired, now.
   * @return inForce
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IN_FORCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getInForce() {
    return inForce;
  }


  @JsonProperty(value = JSON_PROPERTY_IN_FORCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInForce(@jakarta.annotation.Nonnull Boolean inForce) {
    this.inForce = inForce;
  }


  public CustomerAuthorization recordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return recordedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecordedAt() {
    return recordedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
  }


  public CustomerAuthorization recordedBy(@jakarta.annotation.Nonnull UUID recordedBy) {
    this.recordedBy = recordedBy;
    return this;
  }

  /**
   * Get recordedBy
   * @return recordedBy
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getRecordedBy() {
    return recordedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedBy(@jakarta.annotation.Nonnull UUID recordedBy) {
    this.recordedBy = recordedBy;
  }


  public CustomerAuthorization history(@jakarta.annotation.Nonnull List<AuthorizationEvent> history) {
    this.history = history;
    return this;
  }

  public CustomerAuthorization addHistoryItem(AuthorizationEvent historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<>();
    }
    this.history.add(historyItem);
    return this;
  }

  /**
   * Get history
   * @return history
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<AuthorizationEvent> getHistory() {
    return history;
  }


  @JsonProperty(value = JSON_PROPERTY_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHistory(@jakarta.annotation.Nonnull List<AuthorizationEvent> history) {
    this.history = history;
  }


  /**
   * Return true if this CustomerAuthorization object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAuthorization customerAuthorization = (CustomerAuthorization) o;
    return Objects.equals(this.id, customerAuthorization.id) &&
        Objects.equals(this.legalEntityId, customerAuthorization.legalEntityId) &&
        Objects.equals(this.country, customerAuthorization.country) &&
        Objects.equals(this.authority, customerAuthorization.authority) &&
        Objects.equals(this.type, customerAuthorization.type) &&
        Objects.equals(this.permissions, customerAuthorization.permissions) &&
        Objects.equals(this.matters, customerAuthorization.matters) &&
        Objects.equals(this.periodFrom, customerAuthorization.periodFrom) &&
        Objects.equals(this.periodTo, customerAuthorization.periodTo) &&
        Objects.equals(this.representative, customerAuthorization.representative) &&
        Objects.equals(this.effectiveFrom, customerAuthorization.effectiveFrom) &&
        Objects.equals(this.expiresAt, customerAuthorization.expiresAt) &&
        Objects.equals(this.evidence, customerAuthorization.evidence) &&
        Objects.equals(this.credentialRef, customerAuthorization.credentialRef) &&
        Objects.equals(this.supersedes, customerAuthorization.supersedes) &&
        Objects.equals(this.status, customerAuthorization.status) &&
        Objects.equals(this.inForce, customerAuthorization.inForce) &&
        Objects.equals(this.recordedAt, customerAuthorization.recordedAt) &&
        Objects.equals(this.recordedBy, customerAuthorization.recordedBy) &&
        Objects.equals(this.history, customerAuthorization.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, legalEntityId, country, authority, type, permissions, matters, periodFrom, periodTo, representative, effectiveFrom, expiresAt, evidence, credentialRef, supersedes, status, inForce, recordedAt, recordedBy, history);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAuthorization {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    legalEntityId: ").append(toIndentedString(legalEntityId)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    matters: ").append(toIndentedString(matters)).append("\n");
    sb.append("    periodFrom: ").append(toIndentedString(periodFrom)).append("\n");
    sb.append("    periodTo: ").append(toIndentedString(periodTo)).append("\n");
    sb.append("    representative: ").append(toIndentedString(representative)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    evidence: ").append(toIndentedString(evidence)).append("\n");
    sb.append("    credentialRef: ").append(toIndentedString(credentialRef)).append("\n");
    sb.append("    supersedes: ").append(toIndentedString(supersedes)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    inForce: ").append(toIndentedString(inForce)).append("\n");
    sb.append("    recordedAt: ").append(toIndentedString(recordedAt)).append("\n");
    sb.append("    recordedBy: ").append(toIndentedString(recordedBy)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

