/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.BundleRef;
import com.zoikotax.sdk.model.DecisionDigests;
import com.zoikotax.sdk.model.Outcome;
import com.zoikotax.sdk.model.ResultValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * One recorded decision. Immutable; a correction is a new decision whose &#x60;supersedes&#x60; names this one.
 */
@JsonPropertyOrder({
  Decision.JSON_PROPERTY_ID,
  Decision.JSON_PROPERTY_BUSINESS_KEY,
  Decision.JSON_PROPERTY_SUPERSEDES,
  Decision.JSON_PROPERTY_AUTHORITATIVE,
  Decision.JSON_PROPERTY_OUTCOME,
  Decision.JSON_PROPERTY_REASON_CODE,
  Decision.JSON_PROPERTY_EVENT_TIME,
  Decision.JSON_PROPERTY_RECORDED_AT,
  Decision.JSON_PROPERTY_BUNDLE,
  Decision.JSON_PROPERTY_DIGESTS,
  Decision.JSON_PROPERTY_EMITTED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Decision {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_BUSINESS_KEY = "businessKey";
  @jakarta.annotation.Nonnull
  private String businessKey;

  public static final String JSON_PROPERTY_SUPERSEDES = "supersedes";
  @jakarta.annotation.Nullable
  private UUID supersedes;

  public static final String JSON_PROPERTY_AUTHORITATIVE = "authoritative";
  @jakarta.annotation.Nonnull
  private Boolean authoritative;

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @jakarta.annotation.Nonnull
  private Outcome outcome;

  public static final String JSON_PROPERTY_REASON_CODE = "reasonCode";
  @jakarta.annotation.Nonnull
  private String reasonCode;

  public static final String JSON_PROPERTY_EVENT_TIME = "eventTime";
  @jakarta.annotation.Nonnull
  private String eventTime;

  public static final String JSON_PROPERTY_RECORDED_AT = "recordedAt";
  @jakarta.annotation.Nonnull
  private String recordedAt;

  public static final String JSON_PROPERTY_BUNDLE = "bundle";
  @jakarta.annotation.Nonnull
  private BundleRef bundle;

  public static final String JSON_PROPERTY_DIGESTS = "digests";
  @jakarta.annotation.Nonnull
  private DecisionDigests digests;

  public static final String JSON_PROPERTY_EMITTED = "emitted";
  @jakarta.annotation.Nonnull
  private Map<String, ResultValue> emitted;

  public Decision() { 
  }

  public Decision id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * A decision identifier: a UUIDv7 in lowercase canonical form (ADR-0012 §2.1). Sortable by creation, never recycled. 
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public Decision businessKey(@jakarta.annotation.Nonnull String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

  /**
   * The caller&#39;s stable reference for what is being determined — a line, a transaction. It is the identity across corrections: every version of a decision shares it (ADR-0003). Not an identifier this service interprets. 
   * @return businessKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUSINESS_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBusinessKey() {
    return businessKey;
  }


  @JsonProperty(value = JSON_PROPERTY_BUSINESS_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBusinessKey(@jakarta.annotation.Nonnull String businessKey) {
    this.businessKey = businessKey;
  }


  public Decision supersedes(@jakarta.annotation.Nullable UUID supersedes) {
    this.supersedes = supersedes;
    return this;
  }

  /**
   * A decision identifier: a UUIDv7 in lowercase canonical form (ADR-0012 §2.1). Sortable by creation, never recycled. 
   * @return supersedes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPERSEDES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getSupersedes() {
    return supersedes;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPERSEDES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupersedes(@jakarta.annotation.Nullable UUID supersedes) {
    this.supersedes = supersedes;
  }


  public Decision authoritative(@jakarta.annotation.Nonnull Boolean authoritative) {
    this.authoritative = authoritative;
    return this;
  }

  /**
   * Whether this decision may be filed. &#x60;false&#x60; for every decision before A4.
   * @return authoritative
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORITATIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getAuthoritative() {
    return authoritative;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORITATIVE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthoritative(@jakarta.annotation.Nonnull Boolean authoritative) {
    this.authoritative = authoritative;
  }


  public Decision outcome(@jakarta.annotation.Nonnull Outcome outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Outcome getOutcome() {
    return outcome;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@jakarta.annotation.Nonnull Outcome outcome) {
    this.outcome = outcome;
  }


  public Decision reasonCode(@jakarta.annotation.Nonnull String reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

  /**
   * A registered code from a closed vocabulary (ADR-0016 §2.4). Codes are never renumbered, never reused and never redefined; a retired code stops being emitted and keeps its meaning so historical evidence still resolves.  This is the field to branch on. The set this deployment can emit is reported by &#x60;GET /v1/capabilities&#x60;; the enum is deliberately not closed here, because the register grows by addition and a client that rejects an unrecognised code would break on an additive change (ADR-0010 §2.6). 
   * @return reasonCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASON_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReasonCode() {
    return reasonCode;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReasonCode(@jakarta.annotation.Nonnull String reasonCode) {
    this.reasonCode = reasonCode;
  }


  public Decision eventTime(@jakarta.annotation.Nonnull String eventTime) {
    this.eventTime = eventTime;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return eventTime
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEventTime() {
    return eventTime;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_TIME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventTime(@jakarta.annotation.Nonnull String eventTime) {
    this.eventTime = eventTime;
  }


  public Decision recordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return recordedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecordedAt() {
    return recordedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
  }


  public Decision bundle(@jakarta.annotation.Nonnull BundleRef bundle) {
    this.bundle = bundle;
    return this;
  }

  /**
   * Get bundle
   * @return bundle
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUNDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BundleRef getBundle() {
    return bundle;
  }


  @JsonProperty(value = JSON_PROPERTY_BUNDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBundle(@jakarta.annotation.Nonnull BundleRef bundle) {
    this.bundle = bundle;
  }


  public Decision digests(@jakarta.annotation.Nonnull DecisionDigests digests) {
    this.digests = digests;
    return this;
  }

  /**
   * Get digests
   * @return digests
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIGESTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DecisionDigests getDigests() {
    return digests;
  }


  @JsonProperty(value = JSON_PROPERTY_DIGESTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDigests(@jakarta.annotation.Nonnull DecisionDigests digests) {
    this.digests = digests;
  }


  public Decision emitted(@jakarta.annotation.Nonnull Map<String, ResultValue> emitted) {
    this.emitted = emitted;
    return this;
  }

  public Decision putEmittedItem(String key, ResultValue emittedItem) {
    if (this.emitted == null) {
      this.emitted = new HashMap<>();
    }
    this.emitted.put(key, emittedItem);
    return this;
  }

  /**
   * What the content emitted, by result slot. The slots are the pack&#39;s.
   * @return emitted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMITTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, ResultValue> getEmitted() {
    return emitted;
  }


  @JsonProperty(value = JSON_PROPERTY_EMITTED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmitted(@jakarta.annotation.Nonnull Map<String, ResultValue> emitted) {
    this.emitted = emitted;
  }


  /**
   * Return true if this Decision object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Decision decision = (Decision) o;
    return Objects.equals(this.id, decision.id) &&
        Objects.equals(this.businessKey, decision.businessKey) &&
        Objects.equals(this.supersedes, decision.supersedes) &&
        Objects.equals(this.authoritative, decision.authoritative) &&
        Objects.equals(this.outcome, decision.outcome) &&
        Objects.equals(this.reasonCode, decision.reasonCode) &&
        Objects.equals(this.eventTime, decision.eventTime) &&
        Objects.equals(this.recordedAt, decision.recordedAt) &&
        Objects.equals(this.bundle, decision.bundle) &&
        Objects.equals(this.digests, decision.digests) &&
        Objects.equals(this.emitted, decision.emitted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, businessKey, supersedes, authoritative, outcome, reasonCode, eventTime, recordedAt, bundle, digests, emitted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Decision {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    sb.append("    supersedes: ").append(toIndentedString(supersedes)).append("\n");
    sb.append("    authoritative: ").append(toIndentedString(authoritative)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("    eventTime: ").append(toIndentedString(eventTime)).append("\n");
    sb.append("    recordedAt: ").append(toIndentedString(recordedAt)).append("\n");
    sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
    sb.append("    digests: ").append(toIndentedString(digests)).append("\n");
    sb.append("    emitted: ").append(toIndentedString(emitted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

