/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DocumentStatusEvent
 */
@JsonPropertyOrder({
  DocumentStatusEvent.JSON_PROPERTY_SEQ,
  DocumentStatusEvent.JSON_PROPERTY_STATUS,
  DocumentStatusEvent.JSON_PROPERTY_CAUSE_ID,
  DocumentStatusEvent.JSON_PROPERTY_RECORDED_AT,
  DocumentStatusEvent.JSON_PROPERTY_RECORDED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DocumentStatusEvent {
  public static final String JSON_PROPERTY_SEQ = "seq";
  @jakarta.annotation.Nonnull
  private Integer seq;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    COMMITTED(String.valueOf("COMMITTED")),
    
    ISSUED(String.valueOf("ISSUED")),
    
    DELIVERED(String.valueOf("DELIVERED")),
    
    ACCEPTED(String.valueOf("ACCEPTED")),
    
    PARTIALLY_CREDITED(String.valueOf("PARTIALLY_CREDITED")),
    
    FULLY_CREDITED(String.valueOf("FULLY_CREDITED")),
    
    VOIDED(String.valueOf("VOIDED")),
    
    REFUNDED(String.valueOf("REFUNDED")),
    
    AMENDED(String.valueOf("AMENDED")),
    
    DISPUTED(String.valueOf("DISPUTED")),
    
    CLOSED(String.valueOf("CLOSED")),
    
    SUSPENDED(String.valueOf("SUSPENDED")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_CAUSE_ID = "causeId";
  @jakarta.annotation.Nullable
  private UUID causeId;

  public static final String JSON_PROPERTY_RECORDED_AT = "recordedAt";
  @jakarta.annotation.Nonnull
  private String recordedAt;

  public static final String JSON_PROPERTY_RECORDED_BY = "recordedBy";
  @jakarta.annotation.Nullable
  private UUID recordedBy;

  public DocumentStatusEvent() { 
  }

  public DocumentStatusEvent seq(@jakarta.annotation.Nonnull Integer seq) {
    this.seq = seq;
    return this;
  }

  /**
   * Get seq
   * minimum: 1
   * @return seq
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQ, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getSeq() {
    return seq;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQ, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeq(@jakarta.annotation.Nonnull Integer seq) {
    this.seq = seq;
  }


  public DocumentStatusEvent status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public DocumentStatusEvent causeId(@jakarta.annotation.Nullable UUID causeId) {
    this.causeId = causeId;
    return this;
  }

  /**
   * A fiscal document. A UUIDv7 in lowercase canonical form, never the legal document number.
   * @return causeId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAUSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getCauseId() {
    return causeId;
  }


  @JsonProperty(value = JSON_PROPERTY_CAUSE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCauseId(@jakarta.annotation.Nullable UUID causeId) {
    this.causeId = causeId;
  }


  public DocumentStatusEvent recordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return recordedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecordedAt() {
    return recordedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
  }


  public DocumentStatusEvent recordedBy(@jakarta.annotation.Nullable UUID recordedBy) {
    this.recordedBy = recordedBy;
    return this;
  }

  /**
   * Get recordedBy
   * @return recordedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getRecordedBy() {
    return recordedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecordedBy(@jakarta.annotation.Nullable UUID recordedBy) {
    this.recordedBy = recordedBy;
  }


  /**
   * Return true if this DocumentStatusEvent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentStatusEvent documentStatusEvent = (DocumentStatusEvent) o;
    return Objects.equals(this.seq, documentStatusEvent.seq) &&
        Objects.equals(this.status, documentStatusEvent.status) &&
        Objects.equals(this.causeId, documentStatusEvent.causeId) &&
        Objects.equals(this.recordedAt, documentStatusEvent.recordedAt) &&
        Objects.equals(this.recordedBy, documentStatusEvent.recordedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seq, status, causeId, recordedAt, recordedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentStatusEvent {\n");
    sb.append("    seq: ").append(toIndentedString(seq)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    causeId: ").append(toIndentedString(causeId)).append("\n");
    sb.append("    recordedAt: ").append(toIndentedString(recordedAt)).append("\n");
    sb.append("    recordedBy: ").append(toIndentedString(recordedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

