/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.DocumentLineRequest;
import com.zoikotax.sdk.model.ExternalReference;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DocumentRequest
 */
@JsonPropertyOrder({
  DocumentRequest.JSON_PROPERTY_TYPE,
  DocumentRequest.JSON_PROPERTY_NUMBER,
  DocumentRequest.JSON_PROPERTY_ISSUE_DATE,
  DocumentRequest.JSON_PROPERTY_TAX_POINT,
  DocumentRequest.JSON_PROPERTY_CURRENCY,
  DocumentRequest.JSON_PROPERTY_EXTERNAL_REF,
  DocumentRequest.JSON_PROPERTY_LINES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DocumentRequest {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    INVOICE(String.valueOf("INVOICE")),
    
    DEBIT_NOTE(String.valueOf("DEBIT_NOTE")),
    
    ADJUSTMENT(String.valueOf("ADJUSTMENT")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_NUMBER = "number";
  @jakarta.annotation.Nullable
  private String number;

  public static final String JSON_PROPERTY_ISSUE_DATE = "issueDate";
  @jakarta.annotation.Nonnull
  private String issueDate;

  public static final String JSON_PROPERTY_TAX_POINT = "taxPoint";
  @jakarta.annotation.Nonnull
  private String taxPoint;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_EXTERNAL_REF = "externalRef";
  @jakarta.annotation.Nullable
  private ExternalReference externalRef;

  public static final String JSON_PROPERTY_LINES = "lines";
  @jakarta.annotation.Nonnull
  private List<DocumentLineRequest> lines;

  public DocumentRequest() { 
  }

  public DocumentRequest type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public DocumentRequest number(@jakarta.annotation.Nullable String number) {
    this.number = number;
    return this;
  }

  /**
   * The legal, customer-visible document number (ZTAX-FIN-REQ-0006). Kept apart from the id.
   * @return number
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNumber() {
    return number;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumber(@jakarta.annotation.Nullable String number) {
    this.number = number;
  }


  public DocumentRequest issueDate(@jakarta.annotation.Nonnull String issueDate) {
    this.issueDate = issueDate;
    return this;
  }

  /**
   * A calendar date, &#x60;YYYY-MM-DD&#x60;, in a legal calendar the enclosing object names. Not an instant: a due date is a day in the authority&#39;s calendar, and converting it to UTC would move it. 
   * @return issueDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ISSUE_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIssueDate() {
    return issueDate;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssueDate(@jakarta.annotation.Nonnull String issueDate) {
    this.issueDate = issueDate;
  }


  public DocumentRequest taxPoint(@jakarta.annotation.Nonnull String taxPoint) {
    this.taxPoint = taxPoint;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return taxPoint
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAX_POINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTaxPoint() {
    return taxPoint;
  }


  @JsonProperty(value = JSON_PROPERTY_TAX_POINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaxPoint(@jakarta.annotation.Nonnull String taxPoint) {
    this.taxPoint = taxPoint;
  }


  public DocumentRequest currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * An ISO 4217 alphabetic currency code.
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public DocumentRequest externalRef(@jakarta.annotation.Nullable ExternalReference externalRef) {
    this.externalRef = externalRef;
    return this;
  }

  /**
   * Get externalRef
   * @return externalRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ExternalReference getExternalRef() {
    return externalRef;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalRef(@jakarta.annotation.Nullable ExternalReference externalRef) {
    this.externalRef = externalRef;
  }


  public DocumentRequest lines(@jakarta.annotation.Nonnull List<DocumentLineRequest> lines) {
    this.lines = lines;
    return this;
  }

  public DocumentRequest addLinesItem(DocumentLineRequest linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

  /**
   * Get lines
   * @return lines
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DocumentLineRequest> getLines() {
    return lines;
  }


  @JsonProperty(value = JSON_PROPERTY_LINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLines(@jakarta.annotation.Nonnull List<DocumentLineRequest> lines) {
    this.lines = lines;
  }


  /**
   * Return true if this DocumentRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentRequest documentRequest = (DocumentRequest) o;
    return Objects.equals(this.type, documentRequest.type) &&
        Objects.equals(this.number, documentRequest.number) &&
        Objects.equals(this.issueDate, documentRequest.issueDate) &&
        Objects.equals(this.taxPoint, documentRequest.taxPoint) &&
        Objects.equals(this.currency, documentRequest.currency) &&
        Objects.equals(this.externalRef, documentRequest.externalRef) &&
        Objects.equals(this.lines, documentRequest.lines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, number, issueDate, taxPoint, currency, externalRef, lines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    taxPoint: ").append(toIndentedString(taxPoint)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    externalRef: ").append(toIndentedString(externalRef)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

