/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.DocumentTax;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DocumentLine
 */
@JsonPropertyOrder({
  DocumentLine.JSON_PROPERTY_ID,
  DocumentLine.JSON_PROPERTY_SOURCE_LINE_REF,
  DocumentLine.JSON_PROPERTY_COMPONENT_INSTANCE,
  DocumentLine.JSON_PROPERTY_NET,
  DocumentLine.JSON_PROPERTY_DISCOUNT,
  DocumentLine.JSON_PROPERTY_ALLOCATION_REF,
  DocumentLine.JSON_PROPERTY_PREDECESSOR_LINE_ID,
  DocumentLine.JSON_PROPERTY_TAXES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DocumentLine {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_SOURCE_LINE_REF = "sourceLineRef";
  @jakarta.annotation.Nullable
  private String sourceLineRef;

  public static final String JSON_PROPERTY_COMPONENT_INSTANCE = "componentInstance";
  @jakarta.annotation.Nullable
  private String componentInstance;

  public static final String JSON_PROPERTY_NET = "net";
  @jakarta.annotation.Nonnull
  private String net;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  @jakarta.annotation.Nullable
  private String discount;

  public static final String JSON_PROPERTY_ALLOCATION_REF = "allocationRef";
  @jakarta.annotation.Nullable
  private String allocationRef;

  public static final String JSON_PROPERTY_PREDECESSOR_LINE_ID = "predecessorLineId";
  @jakarta.annotation.Nullable
  private UUID predecessorLineId;

  public static final String JSON_PROPERTY_TAXES = "taxes";
  @jakarta.annotation.Nonnull
  private List<DocumentTax> taxes;

  public DocumentLine() { 
  }

  public DocumentLine id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public DocumentLine sourceLineRef(@jakarta.annotation.Nullable String sourceLineRef) {
    this.sourceLineRef = sourceLineRef;
    return this;
  }

  /**
   * The billing or ERP line a document line came from (ZTAX-FIN-REQ-0020).
   * @return sourceLineRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_LINE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSourceLineRef() {
    return sourceLineRef;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_LINE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceLineRef(@jakarta.annotation.Nullable String sourceLineRef) {
    this.sourceLineRef = sourceLineRef;
  }


  public DocumentLine componentInstance(@jakarta.annotation.Nullable String componentInstance) {
    this.componentInstance = componentInstance;
    return this;
  }

  /**
   * Get componentInstance
   * @return componentInstance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPONENT_INSTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getComponentInstance() {
    return componentInstance;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPONENT_INSTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponentInstance(@jakarta.annotation.Nullable String componentInstance) {
    this.componentInstance = componentInstance;
  }


  public DocumentLine net(@jakarta.annotation.Nonnull String net) {
    this.net = net;
    return this;
  }

  /**
   * A decimal in canonical string form (ADR-0010 §2.9): an optional minus, digits, and an optional fraction. No exponent, no leading &#x60;+&#x60;, no leading zeros. **Scale is significant**: &#x60;\&quot;1.50\&quot;&#x60; and &#x60;\&quot;1.5\&quot;&#x60; are different assertions and digest differently.  Classified as fiscal personal data because on a consumer transaction it is: logs carry it redacted, and it is kept for the fiscal record period as evidence. 
   * @return net
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNet() {
    return net;
  }


  @JsonProperty(value = JSON_PROPERTY_NET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNet(@jakarta.annotation.Nonnull String net) {
    this.net = net;
  }


  public DocumentLine discount(@jakarta.annotation.Nullable String discount) {
    this.discount = discount;
    return this;
  }

  /**
   * A decimal in canonical string form (ADR-0010 §2.9): an optional minus, digits, and an optional fraction. No exponent, no leading &#x60;+&#x60;, no leading zeros. **Scale is significant**: &#x60;\&quot;1.50\&quot;&#x60; and &#x60;\&quot;1.5\&quot;&#x60; are different assertions and digest differently.  Classified as fiscal personal data because on a consumer transaction it is: logs carry it redacted, and it is kept for the fiscal record period as evidence. 
   * @return discount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDiscount() {
    return discount;
  }


  @JsonProperty(value = JSON_PROPERTY_DISCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscount(@jakarta.annotation.Nullable String discount) {
    this.discount = discount;
  }


  public DocumentLine allocationRef(@jakarta.annotation.Nullable String allocationRef) {
    this.allocationRef = allocationRef;
    return this;
  }

  /**
   * Get allocationRef
   * @return allocationRef
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOCATION_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAllocationRef() {
    return allocationRef;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOCATION_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllocationRef(@jakarta.annotation.Nullable String allocationRef) {
    this.allocationRef = allocationRef;
  }


  public DocumentLine predecessorLineId(@jakarta.annotation.Nullable UUID predecessorLineId) {
    this.predecessorLineId = predecessorLineId;
    return this;
  }

  /**
   * Get predecessorLineId
   * @return predecessorLineId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREDECESSOR_LINE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getPredecessorLineId() {
    return predecessorLineId;
  }


  @JsonProperty(value = JSON_PROPERTY_PREDECESSOR_LINE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPredecessorLineId(@jakarta.annotation.Nullable UUID predecessorLineId) {
    this.predecessorLineId = predecessorLineId;
  }


  public DocumentLine taxes(@jakarta.annotation.Nonnull List<DocumentTax> taxes) {
    this.taxes = taxes;
    return this;
  }

  public DocumentLine addTaxesItem(DocumentTax taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * Get taxes
   * @return taxes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<DocumentTax> getTaxes() {
    return taxes;
  }


  @JsonProperty(value = JSON_PROPERTY_TAXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaxes(@jakarta.annotation.Nonnull List<DocumentTax> taxes) {
    this.taxes = taxes;
  }


  /**
   * Return true if this DocumentLine object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentLine documentLine = (DocumentLine) o;
    return Objects.equals(this.id, documentLine.id) &&
        Objects.equals(this.sourceLineRef, documentLine.sourceLineRef) &&
        Objects.equals(this.componentInstance, documentLine.componentInstance) &&
        Objects.equals(this.net, documentLine.net) &&
        Objects.equals(this.discount, documentLine.discount) &&
        Objects.equals(this.allocationRef, documentLine.allocationRef) &&
        Objects.equals(this.predecessorLineId, documentLine.predecessorLineId) &&
        Objects.equals(this.taxes, documentLine.taxes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceLineRef, componentInstance, net, discount, allocationRef, predecessorLineId, taxes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentLine {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceLineRef: ").append(toIndentedString(sourceLineRef)).append("\n");
    sb.append("    componentInstance: ").append(toIndentedString(componentInstance)).append("\n");
    sb.append("    net: ").append(toIndentedString(net)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    allocationRef: ").append(toIndentedString(allocationRef)).append("\n");
    sb.append("    predecessorLineId: ").append(toIndentedString(predecessorLineId)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

