/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * One tax on one line, naming the committed decision it comes from and the component the decision&#39;s content posts.
 */
@JsonPropertyOrder({
  DocumentTax.JSON_PROPERTY_DECISION_ID,
  DocumentTax.JSON_PROPERTY_COMPONENT,
  DocumentTax.JSON_PROPERTY_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DocumentTax {
  public static final String JSON_PROPERTY_DECISION_ID = "decisionId";
  @jakarta.annotation.Nonnull
  private UUID decisionId;

  public static final String JSON_PROPERTY_COMPONENT = "component";
  @jakarta.annotation.Nonnull
  private String component;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public DocumentTax() { 
  }

  public DocumentTax decisionId(@jakarta.annotation.Nonnull UUID decisionId) {
    this.decisionId = decisionId;
    return this;
  }

  /**
   * A decision identifier: a UUIDv7 in lowercase canonical form (ADR-0012 §2.1). Sortable by creation, never recycled. 
   * @return decisionId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DECISION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getDecisionId() {
    return decisionId;
  }


  @JsonProperty(value = JSON_PROPERTY_DECISION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecisionId(@jakarta.annotation.Nonnull UUID decisionId) {
    this.decisionId = decisionId;
  }


  public DocumentTax component(@jakarta.annotation.Nonnull String component) {
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPONENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getComponent() {
    return component;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPONENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComponent(@jakarta.annotation.Nonnull String component) {
    this.component = component;
  }


  public DocumentTax amount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * A decimal in canonical string form (ADR-0010 §2.9): an optional minus, digits, and an optional fraction. No exponent, no leading &#x60;+&#x60;, no leading zeros. **Scale is significant**: &#x60;\&quot;1.50\&quot;&#x60; and &#x60;\&quot;1.5\&quot;&#x60; are different assertions and digest differently.  Classified as fiscal personal data because on a consumer transaction it is: logs carry it redacted, and it is kept for the fiscal record period as evidence. 
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  /**
   * Return true if this DocumentTax object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentTax documentTax = (DocumentTax) o;
    return Objects.equals(this.decisionId, documentTax.decisionId) &&
        Objects.equals(this.component, documentTax.component) &&
        Objects.equals(this.amount, documentTax.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(decisionId, component, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentTax {\n");
    sb.append("    decisionId: ").append(toIndentedString(decisionId)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

