/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.JournalLine;
import com.zoikotax.sdk.model.JournalProfile;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * One posted Tax Control Subledger journal. Balanced in its one currency; append-only.
 */
@JsonPropertyOrder({
  Journal.JSON_PROPERTY_ID,
  Journal.JSON_PROPERTY_TYPE,
  Journal.JSON_PROPERTY_LEGAL_ENTITY_ID,
  Journal.JSON_PROPERTY_SOURCE_KIND,
  Journal.JSON_PROPERTY_SOURCE_ID,
  Journal.JSON_PROPERTY_POSTING_DATE,
  Journal.JSON_PROPERTY_LEGAL_PERIOD,
  Journal.JSON_PROPERTY_CURRENCY,
  Journal.JSON_PROPERTY_REVERSAL_OF,
  Journal.JSON_PROPERTY_PROFILE,
  Journal.JSON_PROPERTY_LINES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Journal {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    INVOICE(String.valueOf("INVOICE")),
    
    CREDIT(String.valueOf("CREDIT")),
    
    REFUND(String.valueOf("REFUND")),
    
    LIABILITY_ACCRUAL(String.valueOf("LIABILITY_ACCRUAL")),
    
    RETURN(String.valueOf("RETURN")),
    
    REMITTANCE(String.valueOf("REMITTANCE")),
    
    FX(String.valueOf("FX")),
    
    ROUNDING(String.valueOf("ROUNDING")),
    
    MIGRATION(String.valueOf("MIGRATION")),
    
    ADJUSTMENT(String.valueOf("ADJUSTMENT")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_ID = "legalEntityId";
  @jakarta.annotation.Nonnull
  private UUID legalEntityId;

  public static final String JSON_PROPERTY_SOURCE_KIND = "sourceKind";
  @jakarta.annotation.Nonnull
  private String sourceKind;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  @jakarta.annotation.Nonnull
  private String sourceId;

  public static final String JSON_PROPERTY_POSTING_DATE = "postingDate";
  @jakarta.annotation.Nonnull
  private String postingDate;

  public static final String JSON_PROPERTY_LEGAL_PERIOD = "legalPeriod";
  @jakarta.annotation.Nonnull
  private String legalPeriod;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_REVERSAL_OF = "reversalOf";
  @jakarta.annotation.Nullable
  private UUID reversalOf;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @jakarta.annotation.Nonnull
  private JournalProfile profile;

  public static final String JSON_PROPERTY_LINES = "lines";
  @jakarta.annotation.Nonnull
  private List<JournalLine> lines;

  public Journal() { 
  }

  public Journal id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public Journal type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Journal legalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
    return this;
  }

  /**
   * A legal entity within the tenant (ZTAX-OBL-REQ-0018). A UUID in lowercase canonical form.
   * @return legalEntityId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getLegalEntityId() {
    return legalEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
  }


  public Journal sourceKind(@jakarta.annotation.Nonnull String sourceKind) {
    this.sourceKind = sourceKind;
    return this;
  }

  /**
   * The source event kind, e.g. &#x60;DECISION_COMMITTED&#x60; or &#x60;DECISION_SUPERSEDED&#x60;.
   * @return sourceKind
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSourceKind() {
    return sourceKind;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceKind(@jakarta.annotation.Nonnull String sourceKind) {
    this.sourceKind = sourceKind;
  }


  public Journal sourceId(@jakarta.annotation.Nonnull String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

  /**
   * Get sourceId
   * @return sourceId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceId(@jakarta.annotation.Nonnull String sourceId) {
    this.sourceId = sourceId;
  }


  public Journal postingDate(@jakarta.annotation.Nonnull String postingDate) {
    this.postingDate = postingDate;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return postingDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POSTING_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPostingDate() {
    return postingDate;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTING_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPostingDate(@jakarta.annotation.Nonnull String postingDate) {
    this.postingDate = postingDate;
  }


  public Journal legalPeriod(@jakarta.annotation.Nonnull String legalPeriod) {
    this.legalPeriod = legalPeriod;
    return this;
  }

  /**
   * Get legalPeriod
   * @return legalPeriod
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEGAL_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLegalPeriod() {
    return legalPeriod;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalPeriod(@jakarta.annotation.Nonnull String legalPeriod) {
    this.legalPeriod = legalPeriod;
  }


  public Journal currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * An ISO 4217 alphabetic currency code.
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Journal reversalOf(@jakarta.annotation.Nullable UUID reversalOf) {
    this.reversalOf = reversalOf;
    return this;
  }

  /**
   * The journal this one reverses, for a reversal.
   * @return reversalOf
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REVERSAL_OF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getReversalOf() {
    return reversalOf;
  }


  @JsonProperty(value = JSON_PROPERTY_REVERSAL_OF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReversalOf(@jakarta.annotation.Nullable UUID reversalOf) {
    this.reversalOf = reversalOf;
  }


  public Journal profile(@jakarta.annotation.Nonnull JournalProfile profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROFILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public JournalProfile getProfile() {
    return profile;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfile(@jakarta.annotation.Nonnull JournalProfile profile) {
    this.profile = profile;
  }


  public Journal lines(@jakarta.annotation.Nonnull List<JournalLine> lines) {
    this.lines = lines;
    return this;
  }

  public Journal addLinesItem(JournalLine linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

  /**
   * Get lines
   * @return lines
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<JournalLine> getLines() {
    return lines;
  }


  @JsonProperty(value = JSON_PROPERTY_LINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLines(@jakarta.annotation.Nonnull List<JournalLine> lines) {
    this.lines = lines;
  }


  /**
   * Return true if this Journal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Journal journal = (Journal) o;
    return Objects.equals(this.id, journal.id) &&
        Objects.equals(this.type, journal.type) &&
        Objects.equals(this.legalEntityId, journal.legalEntityId) &&
        Objects.equals(this.sourceKind, journal.sourceKind) &&
        Objects.equals(this.sourceId, journal.sourceId) &&
        Objects.equals(this.postingDate, journal.postingDate) &&
        Objects.equals(this.legalPeriod, journal.legalPeriod) &&
        Objects.equals(this.currency, journal.currency) &&
        Objects.equals(this.reversalOf, journal.reversalOf) &&
        Objects.equals(this.profile, journal.profile) &&
        Objects.equals(this.lines, journal.lines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, legalEntityId, sourceKind, sourceId, postingDate, legalPeriod, currency, reversalOf, profile, lines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Journal {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    legalEntityId: ").append(toIndentedString(legalEntityId)).append("\n");
    sb.append("    sourceKind: ").append(toIndentedString(sourceKind)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    postingDate: ").append(toIndentedString(postingDate)).append("\n");
    sb.append("    legalPeriod: ").append(toIndentedString(legalPeriod)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    reversalOf: ").append(toIndentedString(reversalOf)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

