/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.AuthorizationType;
import com.zoikotax.sdk.model.FundsPosture;
import com.zoikotax.sdk.model.LegalStatus;
import com.zoikotax.sdk.model.ServiceState;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * LegalRule
 */
@JsonPropertyOrder({
  LegalRule.JSON_PROPERTY_ID,
  LegalRule.JSON_PROPERTY_VERSION,
  LegalRule.JSON_PROPERTY_COUNTRY,
  LegalRule.JSON_PROPERTY_AUTHORITY,
  LegalRule.JSON_PROPERTY_SERVICE,
  LegalRule.JSON_PROPERTY_STATUS,
  LegalRule.JSON_PROPERTY_PROVIDER,
  LegalRule.JSON_PROPERTY_AUTHORIZATION_TYPE,
  LegalRule.JSON_PROPERTY_REQUIRES_PERIODS,
  LegalRule.JSON_PROPERTY_REQUIRES_MATTERS,
  LegalRule.JSON_PROPERTY_QUALIFICATION,
  LegalRule.JSON_PROPERTY_CREDENTIAL,
  LegalRule.JSON_PROPERTY_FUNDS,
  LegalRule.JSON_PROPERTY_OPINION_REF,
  LegalRule.JSON_PROPERTY_EFFECTIVE_FROM,
  LegalRule.JSON_PROPERTY_EFFECTIVE_TO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class LegalRule {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nonnull
  private Integer version;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nonnull
  private String country;

  public static final String JSON_PROPERTY_AUTHORITY = "authority";
  @jakarta.annotation.Nonnull
  private String authority;

  public static final String JSON_PROPERTY_SERVICE = "service";
  @jakarta.annotation.Nonnull
  private ServiceState service;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private LegalStatus status;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nonnull
  private String provider;

  public static final String JSON_PROPERTY_AUTHORIZATION_TYPE = "authorizationType";
  @jakarta.annotation.Nonnull
  private AuthorizationType authorizationType;

  public static final String JSON_PROPERTY_REQUIRES_PERIODS = "requiresPeriods";
  @jakarta.annotation.Nonnull
  private Boolean requiresPeriods;

  public static final String JSON_PROPERTY_REQUIRES_MATTERS = "requiresMatters";
  @jakarta.annotation.Nonnull
  private Boolean requiresMatters;

  public static final String JSON_PROPERTY_QUALIFICATION = "qualification";
  @jakarta.annotation.Nullable
  private String qualification;

  public static final String JSON_PROPERTY_CREDENTIAL = "credential";
  @jakarta.annotation.Nullable
  private String credential;

  public static final String JSON_PROPERTY_FUNDS = "funds";
  @jakarta.annotation.Nonnull
  private FundsPosture funds;

  public static final String JSON_PROPERTY_OPINION_REF = "opinionRef";
  @jakarta.annotation.Nonnull
  private String opinionRef;

  public static final String JSON_PROPERTY_EFFECTIVE_FROM = "effectiveFrom";
  @jakarta.annotation.Nonnull
  private String effectiveFrom;

  public static final String JSON_PROPERTY_EFFECTIVE_TO = "effectiveTo";
  @jakarta.annotation.Nullable
  private String effectiveTo;

  public LegalRule() { 
  }

  public LegalRule id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public LegalRule version(@jakarta.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@jakarta.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public LegalRule country(@jakarta.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2.
   * @return country
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountry(@jakarta.annotation.Nonnull String country) {
    this.country = country;
  }


  public LegalRule authority(@jakarta.annotation.Nonnull String authority) {
    this.authority = authority;
    return this;
  }

  /**
   * An authority within a country, as the matrix names it.
   * @return authority
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAuthority() {
    return authority;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthority(@jakarta.annotation.Nonnull String authority) {
    this.authority = authority;
  }


  public LegalRule service(@jakarta.annotation.Nonnull ServiceState service) {
    this.service = service;
    return this;
  }

  /**
   * Get service
   * @return service
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ServiceState getService() {
    return service;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setService(@jakarta.annotation.Nonnull ServiceState service) {
    this.service = service;
  }


  public LegalRule status(@jakarta.annotation.Nonnull LegalStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LegalStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull LegalStatus status) {
    this.status = status;
  }


  public LegalRule provider(@jakarta.annotation.Nonnull String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * The Zoiko entity or approved partner that performs the service.
   * @return provider
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@jakarta.annotation.Nonnull String provider) {
    this.provider = provider;
  }


  public LegalRule authorizationType(@jakarta.annotation.Nonnull AuthorizationType authorizationType) {
    this.authorizationType = authorizationType;
    return this;
  }

  /**
   * Get authorizationType
   * @return authorizationType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHORIZATION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthorizationType getAuthorizationType() {
    return authorizationType;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHORIZATION_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthorizationType(@jakarta.annotation.Nonnull AuthorizationType authorizationType) {
    this.authorizationType = authorizationType;
  }


  public LegalRule requiresPeriods(@jakarta.annotation.Nonnull Boolean requiresPeriods) {
    this.requiresPeriods = requiresPeriods;
    return this;
  }

  /**
   * The authority accepts no generic grant; an authorization names its periods.
   * @return requiresPeriods
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUIRES_PERIODS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getRequiresPeriods() {
    return requiresPeriods;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRES_PERIODS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequiresPeriods(@jakarta.annotation.Nonnull Boolean requiresPeriods) {
    this.requiresPeriods = requiresPeriods;
  }


  public LegalRule requiresMatters(@jakarta.annotation.Nonnull Boolean requiresMatters) {
    this.requiresMatters = requiresMatters;
    return this;
  }

  /**
   * The authority accepts no generic grant; an authorization names its matters.
   * @return requiresMatters
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUIRES_MATTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getRequiresMatters() {
    return requiresMatters;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRES_MATTERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequiresMatters(@jakarta.annotation.Nonnull Boolean requiresMatters) {
    this.requiresMatters = requiresMatters;
  }


  public LegalRule qualification(@jakarta.annotation.Nullable String qualification) {
    this.qualification = qualification;
    return this;
  }

  /**
   * Get qualification
   * @return qualification
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUALIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQualification() {
    return qualification;
  }


  @JsonProperty(value = JSON_PROPERTY_QUALIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualification(@jakarta.annotation.Nullable String qualification) {
    this.qualification = qualification;
  }


  public LegalRule credential(@jakarta.annotation.Nullable String credential) {
    this.credential = credential;
    return this;
  }

  /**
   * The kind of credential the authority needs — never a credential.
   * @return credential
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCredential() {
    return credential;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredential(@jakarta.annotation.Nullable String credential) {
    this.credential = credential;
  }


  public LegalRule funds(@jakarta.annotation.Nonnull FundsPosture funds) {
    this.funds = funds;
    return this;
  }

  /**
   * Get funds
   * @return funds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FundsPosture getFunds() {
    return funds;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunds(@jakarta.annotation.Nonnull FundsPosture funds) {
    this.funds = funds;
  }


  public LegalRule opinionRef(@jakarta.annotation.Nonnull String opinionRef) {
    this.opinionRef = opinionRef;
    return this;
  }

  /**
   * The counsel memo or authority source the rule rests on.
   * @return opinionRef
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPINION_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOpinionRef() {
    return opinionRef;
  }


  @JsonProperty(value = JSON_PROPERTY_OPINION_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOpinionRef(@jakarta.annotation.Nonnull String opinionRef) {
    this.opinionRef = opinionRef;
  }


  public LegalRule effectiveFrom(@jakarta.annotation.Nonnull String effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return effectiveFrom
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEffectiveFrom() {
    return effectiveFrom;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEffectiveFrom(@jakarta.annotation.Nonnull String effectiveFrom) {
    this.effectiveFrom = effectiveFrom;
  }


  public LegalRule effectiveTo(@jakarta.annotation.Nullable String effectiveTo) {
    this.effectiveTo = effectiveTo;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return effectiveTo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEffectiveTo() {
    return effectiveTo;
  }


  @JsonProperty(value = JSON_PROPERTY_EFFECTIVE_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEffectiveTo(@jakarta.annotation.Nullable String effectiveTo) {
    this.effectiveTo = effectiveTo;
  }


  /**
   * Return true if this LegalRule object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalRule legalRule = (LegalRule) o;
    return Objects.equals(this.id, legalRule.id) &&
        Objects.equals(this.version, legalRule.version) &&
        Objects.equals(this.country, legalRule.country) &&
        Objects.equals(this.authority, legalRule.authority) &&
        Objects.equals(this.service, legalRule.service) &&
        Objects.equals(this.status, legalRule.status) &&
        Objects.equals(this.provider, legalRule.provider) &&
        Objects.equals(this.authorizationType, legalRule.authorizationType) &&
        Objects.equals(this.requiresPeriods, legalRule.requiresPeriods) &&
        Objects.equals(this.requiresMatters, legalRule.requiresMatters) &&
        Objects.equals(this.qualification, legalRule.qualification) &&
        Objects.equals(this.credential, legalRule.credential) &&
        Objects.equals(this.funds, legalRule.funds) &&
        Objects.equals(this.opinionRef, legalRule.opinionRef) &&
        Objects.equals(this.effectiveFrom, legalRule.effectiveFrom) &&
        Objects.equals(this.effectiveTo, legalRule.effectiveTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, country, authority, service, status, provider, authorizationType, requiresPeriods, requiresMatters, qualification, credential, funds, opinionRef, effectiveFrom, effectiveTo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalRule {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    authorizationType: ").append(toIndentedString(authorizationType)).append("\n");
    sb.append("    requiresPeriods: ").append(toIndentedString(requiresPeriods)).append("\n");
    sb.append("    requiresMatters: ").append(toIndentedString(requiresMatters)).append("\n");
    sb.append("    qualification: ").append(toIndentedString(qualification)).append("\n");
    sb.append("    credential: ").append(toIndentedString(credential)).append("\n");
    sb.append("    funds: ").append(toIndentedString(funds)).append("\n");
    sb.append("    opinionRef: ").append(toIndentedString(opinionRef)).append("\n");
    sb.append("    effectiveFrom: ").append(toIndentedString(effectiveFrom)).append("\n");
    sb.append("    effectiveTo: ").append(toIndentedString(effectiveTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

