/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ObligationContent
 */
@JsonPropertyOrder({
  ObligationContent.JSON_PROPERTY_BUNDLE_ID,
  ObligationContent.JSON_PROPERTY_BUNDLE_DIGEST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ObligationContent {
  public static final String JSON_PROPERTY_BUNDLE_ID = "bundleId";
  @jakarta.annotation.Nonnull
  private String bundleId;

  public static final String JSON_PROPERTY_BUNDLE_DIGEST = "bundleDigest";
  @jakarta.annotation.Nonnull
  private String bundleDigest;

  public ObligationContent() { 
  }

  public ObligationContent bundleId(@jakarta.annotation.Nonnull String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

  /**
   * Get bundleId
   * @return bundleId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBundleId() {
    return bundleId;
  }


  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBundleId(@jakarta.annotation.Nonnull String bundleId) {
    this.bundleId = bundleId;
  }


  public ObligationContent bundleDigest(@jakarta.annotation.Nonnull String bundleDigest) {
    this.bundleDigest = bundleDigest;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return bundleDigest
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BUNDLE_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBundleDigest() {
    return bundleDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_BUNDLE_DIGEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBundleDigest(@jakarta.annotation.Nonnull String bundleDigest) {
    this.bundleDigest = bundleDigest;
  }


  /**
   * Return true if this Obligation_content object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObligationContent obligationContent = (ObligationContent) o;
    return Objects.equals(this.bundleId, obligationContent.bundleId) &&
        Objects.equals(this.bundleDigest, obligationContent.bundleDigest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleId, bundleDigest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObligationContent {\n");
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    bundleDigest: ").append(toIndentedString(bundleDigest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

