/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.PeriodState;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PeriodEvent
 */
@JsonPropertyOrder({
  PeriodEvent.JSON_PROPERTY_SEQ,
  PeriodEvent.JSON_PROPERTY_STATE,
  PeriodEvent.JSON_PROPERTY_REASON,
  PeriodEvent.JSON_PROPERTY_RECORDED_AT,
  PeriodEvent.JSON_PROPERTY_RECORDED_BY,
  PeriodEvent.JSON_PROPERTY_APPROVED_BY,
  PeriodEvent.JSON_PROPERTY_REQUEST_ID,
  PeriodEvent.JSON_PROPERTY_MANIFEST_DIGEST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class PeriodEvent {
  public static final String JSON_PROPERTY_SEQ = "seq";
  @jakarta.annotation.Nonnull
  private Integer seq;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nonnull
  private PeriodState state;

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_RECORDED_AT = "recordedAt";
  @jakarta.annotation.Nonnull
  private String recordedAt;

  public static final String JSON_PROPERTY_RECORDED_BY = "recordedBy";
  @jakarta.annotation.Nullable
  private UUID recordedBy;

  public static final String JSON_PROPERTY_APPROVED_BY = "approvedBy";
  @jakarta.annotation.Nullable
  private UUID approvedBy;

  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  @jakarta.annotation.Nullable
  private UUID requestId;

  public static final String JSON_PROPERTY_MANIFEST_DIGEST = "manifestDigest";
  @jakarta.annotation.Nullable
  private String manifestDigest;

  public PeriodEvent() { 
  }

  public PeriodEvent seq(@jakarta.annotation.Nonnull Integer seq) {
    this.seq = seq;
    return this;
  }

  /**
   * Get seq
   * minimum: 1
   * @return seq
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQ, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getSeq() {
    return seq;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQ, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeq(@jakarta.annotation.Nonnull Integer seq) {
    this.seq = seq;
  }


  public PeriodEvent state(@jakarta.annotation.Nonnull PeriodState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PeriodState getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@jakarta.annotation.Nonnull PeriodState state) {
    this.state = state;
  }


  public PeriodEvent reason(@jakarta.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Free text entered by an operator.
   * @return reason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@jakarta.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public PeriodEvent recordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return recordedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecordedAt() {
    return recordedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordedAt(@jakarta.annotation.Nonnull String recordedAt) {
    this.recordedAt = recordedAt;
  }


  public PeriodEvent recordedBy(@jakarta.annotation.Nullable UUID recordedBy) {
    this.recordedBy = recordedBy;
    return this;
  }

  /**
   * Who moved the period; on a reopening, who requested it.
   * @return recordedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getRecordedBy() {
    return recordedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecordedBy(@jakarta.annotation.Nullable UUID recordedBy) {
    this.recordedBy = recordedBy;
  }


  public PeriodEvent approvedBy(@jakarta.annotation.Nullable UUID approvedBy) {
    this.approvedBy = approvedBy;
    return this;
  }

  /**
   * On a reopening, the second person who approved it.
   * @return approvedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APPROVED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getApprovedBy() {
    return approvedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_APPROVED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApprovedBy(@jakarta.annotation.Nullable UUID approvedBy) {
    this.approvedBy = approvedBy;
  }


  public PeriodEvent requestId(@jakarta.annotation.Nullable UUID requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@jakarta.annotation.Nullable UUID requestId) {
    this.requestId = requestId;
  }


  public PeriodEvent manifestDigest(@jakarta.annotation.Nullable String manifestDigest) {
    this.manifestDigest = manifestDigest;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return manifestDigest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANIFEST_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getManifestDigest() {
    return manifestDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_MANIFEST_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManifestDigest(@jakarta.annotation.Nullable String manifestDigest) {
    this.manifestDigest = manifestDigest;
  }


  /**
   * Return true if this PeriodEvent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeriodEvent periodEvent = (PeriodEvent) o;
    return Objects.equals(this.seq, periodEvent.seq) &&
        Objects.equals(this.state, periodEvent.state) &&
        Objects.equals(this.reason, periodEvent.reason) &&
        Objects.equals(this.recordedAt, periodEvent.recordedAt) &&
        Objects.equals(this.recordedBy, periodEvent.recordedBy) &&
        Objects.equals(this.approvedBy, periodEvent.approvedBy) &&
        Objects.equals(this.requestId, periodEvent.requestId) &&
        Objects.equals(this.manifestDigest, periodEvent.manifestDigest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seq, state, reason, recordedAt, recordedBy, approvedBy, requestId, manifestDigest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeriodEvent {\n");
    sb.append("    seq: ").append(toIndentedString(seq)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    recordedAt: ").append(toIndentedString(recordedAt)).append("\n");
    sb.append("    recordedBy: ").append(toIndentedString(recordedBy)).append("\n");
    sb.append("    approvedBy: ").append(toIndentedString(approvedBy)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    manifestDigest: ").append(toIndentedString(manifestDigest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

