/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.ReconStage;
import com.zoikotax.sdk.model.ReconciliationItem;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ReconciliationRun
 */
@JsonPropertyOrder({
  ReconciliationRun.JSON_PROPERTY_ID,
  ReconciliationRun.JSON_PROPERTY_PERIOD,
  ReconciliationRun.JSON_PROPERTY_LEGAL_ENTITY_ID,
  ReconciliationRun.JSON_PROPERTY_RAN_AT,
  ReconciliationRun.JSON_PROPERTY_RAN_BY,
  ReconciliationRun.JSON_PROPERTY_FIRST_BREAK,
  ReconciliationRun.JSON_PROPERTY_UNAVAILABLE,
  ReconciliationRun.JSON_PROPERTY_ITEMS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ReconciliationRun {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PERIOD = "period";
  @jakarta.annotation.Nonnull
  private String period;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_ID = "legalEntityId";
  @jakarta.annotation.Nonnull
  private UUID legalEntityId;

  public static final String JSON_PROPERTY_RAN_AT = "ranAt";
  @jakarta.annotation.Nonnull
  private String ranAt;

  public static final String JSON_PROPERTY_RAN_BY = "ranBy";
  @jakarta.annotation.Nullable
  private UUID ranBy;

  public static final String JSON_PROPERTY_FIRST_BREAK = "firstBreak";
  @jakarta.annotation.Nullable
  private ReconStage firstBreak;

  public static final String JSON_PROPERTY_UNAVAILABLE = "unavailable";
  @jakarta.annotation.Nonnull
  private List<ReconStage> unavailable;

  public static final String JSON_PROPERTY_ITEMS = "items";
  @jakarta.annotation.Nonnull
  private List<ReconciliationItem> items;

  public ReconciliationRun() { 
  }

  public ReconciliationRun id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public ReconciliationRun period(@jakarta.annotation.Nonnull String period) {
    this.period = period;
    return this;
  }

  /**
   * A subledger legal period, a month.
   * @return period
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPeriod() {
    return period;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriod(@jakarta.annotation.Nonnull String period) {
    this.period = period;
  }


  public ReconciliationRun legalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
    return this;
  }

  /**
   * A legal entity within the tenant (ZTAX-OBL-REQ-0018). A UUID in lowercase canonical form.
   * @return legalEntityId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getLegalEntityId() {
    return legalEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
  }


  public ReconciliationRun ranAt(@jakarta.annotation.Nonnull String ranAt) {
    this.ranAt = ranAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return ranAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RAN_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRanAt() {
    return ranAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RAN_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRanAt(@jakarta.annotation.Nonnull String ranAt) {
    this.ranAt = ranAt;
  }


  public ReconciliationRun ranBy(@jakarta.annotation.Nullable UUID ranBy) {
    this.ranBy = ranBy;
    return this;
  }

  /**
   * Get ranBy
   * @return ranBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RAN_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getRanBy() {
    return ranBy;
  }


  @JsonProperty(value = JSON_PROPERTY_RAN_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRanBy(@jakarta.annotation.Nullable UUID ranBy) {
    this.ranBy = ranBy;
  }


  public ReconciliationRun firstBreak(@jakarta.annotation.Nullable ReconStage firstBreak) {
    this.firstBreak = firstBreak;
    return this;
  }

  /**
   * Get firstBreak
   * @return firstBreak
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_BREAK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ReconStage getFirstBreak() {
    return firstBreak;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_BREAK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstBreak(@jakarta.annotation.Nullable ReconStage firstBreak) {
    this.firstBreak = firstBreak;
  }


  public ReconciliationRun unavailable(@jakarta.annotation.Nonnull List<ReconStage> unavailable) {
    this.unavailable = unavailable;
    return this;
  }

  public ReconciliationRun addUnavailableItem(ReconStage unavailableItem) {
    if (this.unavailable == null) {
      this.unavailable = new ArrayList<>();
    }
    this.unavailable.add(unavailableItem);
    return this;
  }

  /**
   * Get unavailable
   * @return unavailable
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNAVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ReconStage> getUnavailable() {
    return unavailable;
  }


  @JsonProperty(value = JSON_PROPERTY_UNAVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnavailable(@jakarta.annotation.Nonnull List<ReconStage> unavailable) {
    this.unavailable = unavailable;
  }


  public ReconciliationRun items(@jakarta.annotation.Nonnull List<ReconciliationItem> items) {
    this.items = items;
    return this;
  }

  public ReconciliationRun addItemsItem(ReconciliationItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ReconciliationItem> getItems() {
    return items;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(@jakarta.annotation.Nonnull List<ReconciliationItem> items) {
    this.items = items;
  }


  /**
   * Return true if this ReconciliationRun object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReconciliationRun reconciliationRun = (ReconciliationRun) o;
    return Objects.equals(this.id, reconciliationRun.id) &&
        Objects.equals(this.period, reconciliationRun.period) &&
        Objects.equals(this.legalEntityId, reconciliationRun.legalEntityId) &&
        Objects.equals(this.ranAt, reconciliationRun.ranAt) &&
        Objects.equals(this.ranBy, reconciliationRun.ranBy) &&
        Objects.equals(this.firstBreak, reconciliationRun.firstBreak) &&
        Objects.equals(this.unavailable, reconciliationRun.unavailable) &&
        Objects.equals(this.items, reconciliationRun.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, period, legalEntityId, ranAt, ranBy, firstBreak, unavailable, items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReconciliationRun {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    legalEntityId: ").append(toIndentedString(legalEntityId)).append("\n");
    sb.append("    ranAt: ").append(toIndentedString(ranAt)).append("\n");
    sb.append("    ranBy: ").append(toIndentedString(ranBy)).append("\n");
    sb.append("    firstBreak: ").append(toIndentedString(firstBreak)).append("\n");
    sb.append("    unavailable: ").append(toIndentedString(unavailable)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

