/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.RootCause;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ResolutionRequest
 */
@JsonPropertyOrder({
  ResolutionRequest.JSON_PROPERTY_REASON,
  ResolutionRequest.JSON_PROPERTY_ACTION,
  ResolutionRequest.JSON_PROPERTY_ROOT_CAUSE,
  ResolutionRequest.JSON_PROPERTY_EVIDENCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ResolutionRequest {
  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nonnull
  private String reason;

  /**
   * Gets or Sets action
   */
  public enum ActionEnum {
    ADJUST(String.valueOf("ADJUST")),
    
    RECLASSIFY(String.valueOf("RECLASSIFY")),
    
    AMEND(String.valueOf("AMEND")),
    
    WAIT(String.valueOf("WAIT")),
    
    WAIVE_WITH_APPROVAL(String.valueOf("WAIVE_WITH_APPROVAL")),
    
    EXTERNAL_CORRECTION(String.valueOf("EXTERNAL_CORRECTION")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nonnull
  private ActionEnum action;

  public static final String JSON_PROPERTY_ROOT_CAUSE = "rootCause";
  @jakarta.annotation.Nonnull
  private RootCause rootCause;

  public static final String JSON_PROPERTY_EVIDENCE = "evidence";
  @jakarta.annotation.Nonnull
  private List<String> evidence;

  public ResolutionRequest() { 
  }

  public ResolutionRequest reason(@jakarta.annotation.Nonnull String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(@jakarta.annotation.Nonnull String reason) {
    this.reason = reason;
  }


  public ResolutionRequest action(@jakarta.annotation.Nonnull ActionEnum action) {
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@jakarta.annotation.Nonnull ActionEnum action) {
    this.action = action;
  }


  public ResolutionRequest rootCause(@jakarta.annotation.Nonnull RootCause rootCause) {
    this.rootCause = rootCause;
    return this;
  }

  /**
   * Get rootCause
   * @return rootCause
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROOT_CAUSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RootCause getRootCause() {
    return rootCause;
  }


  @JsonProperty(value = JSON_PROPERTY_ROOT_CAUSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRootCause(@jakarta.annotation.Nonnull RootCause rootCause) {
    this.rootCause = rootCause;
  }


  public ResolutionRequest evidence(@jakarta.annotation.Nonnull List<String> evidence) {
    this.evidence = evidence;
    return this;
  }

  public ResolutionRequest addEvidenceItem(String evidenceItem) {
    if (this.evidence == null) {
      this.evidence = new ArrayList<>();
    }
    this.evidence.add(evidenceItem);
    return this;
  }

  /**
   * Get evidence
   * @return evidence
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getEvidence() {
    return evidence;
  }


  @JsonProperty(value = JSON_PROPERTY_EVIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidence(@jakarta.annotation.Nonnull List<String> evidence) {
    this.evidence = evidence;
  }


  /**
   * Return true if this ResolutionRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolutionRequest resolutionRequest = (ResolutionRequest) o;
    return Objects.equals(this.reason, resolutionRequest.reason) &&
        Objects.equals(this.action, resolutionRequest.action) &&
        Objects.equals(this.rootCause, resolutionRequest.rootCause) &&
        Objects.equals(this.evidence, resolutionRequest.evidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, action, rootCause, evidence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolutionRequest {\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    rootCause: ").append(toIndentedString(rootCause)).append("\n");
    sb.append("    evidence: ").append(toIndentedString(evidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

