/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.PolicyVersionRef;
import com.zoikotax.sdk.model.RetentionRecordClass;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RetentionVerdict
 */
@JsonPropertyOrder({
  RetentionVerdict.JSON_PROPERTY_DECISION_ID,
  RetentionVerdict.JSON_PROPERTY_RECORD_CLASS,
  RetentionVerdict.JSON_PROPERTY_COUNTRY,
  RetentionVerdict.JSON_PROPERTY_OUTCOME,
  RetentionVerdict.JSON_PROPERTY_POLICY,
  RetentionVerdict.JSON_PROPERTY_CANDIDATES,
  RetentionVerdict.JSON_PROPERTY_RETAIN_UNTIL,
  RetentionVerdict.JSON_PROPERTY_HOLDS,
  RetentionVerdict.JSON_PROPERTY_DETAIL,
  RetentionVerdict.JSON_PROPERTY_EVALUATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class RetentionVerdict {
  public static final String JSON_PROPERTY_DECISION_ID = "decisionId";
  @jakarta.annotation.Nonnull
  private UUID decisionId;

  public static final String JSON_PROPERTY_RECORD_CLASS = "recordClass";
  @jakarta.annotation.Nonnull
  private RetentionRecordClass recordClass;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @jakarta.annotation.Nullable
  private String country;

  /**
   * Gets or Sets outcome
   */
  public enum OutcomeEnum {
    RETAIN(String.valueOf("RETAIN")),
    
    HELD(String.valueOf("HELD")),
    
    ELIGIBLE(String.valueOf("ELIGIBLE")),
    
    NO_POLICY(String.valueOf("NO_POLICY")),
    
    CONFLICTED(String.valueOf("CONFLICTED")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    OutcomeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OutcomeEnum fromValue(String value) {
      for (OutcomeEnum b : OutcomeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  @jakarta.annotation.Nonnull
  private OutcomeEnum outcome;

  public static final String JSON_PROPERTY_POLICY = "policy";
  @jakarta.annotation.Nullable
  private PolicyVersionRef policy;

  public static final String JSON_PROPERTY_CANDIDATES = "candidates";
  @jakarta.annotation.Nullable
  private List<PolicyVersionRef> candidates;

  public static final String JSON_PROPERTY_RETAIN_UNTIL = "retainUntil";
  @jakarta.annotation.Nullable
  private String retainUntil;

  public static final String JSON_PROPERTY_HOLDS = "holds";
  @jakarta.annotation.Nullable
  private List<UUID> holds;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  @jakarta.annotation.Nullable
  private String detail;

  public static final String JSON_PROPERTY_EVALUATED_AT = "evaluatedAt";
  @jakarta.annotation.Nonnull
  private String evaluatedAt;

  public RetentionVerdict() { 
  }

  public RetentionVerdict decisionId(@jakarta.annotation.Nonnull UUID decisionId) {
    this.decisionId = decisionId;
    return this;
  }

  /**
   * A decision identifier: a UUIDv7 in lowercase canonical form (ADR-0012 §2.1). Sortable by creation, never recycled. 
   * @return decisionId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DECISION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getDecisionId() {
    return decisionId;
  }


  @JsonProperty(value = JSON_PROPERTY_DECISION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecisionId(@jakarta.annotation.Nonnull UUID decisionId) {
    this.decisionId = decisionId;
  }


  public RetentionVerdict recordClass(@jakarta.annotation.Nonnull RetentionRecordClass recordClass) {
    this.recordClass = recordClass;
    return this;
  }

  /**
   * Get recordClass
   * @return recordClass
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORD_CLASS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RetentionRecordClass getRecordClass() {
    return recordClass;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORD_CLASS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordClass(@jakarta.annotation.Nonnull RetentionRecordClass recordClass) {
    this.recordClass = recordClass;
  }


  public RetentionVerdict country(@jakarta.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2.
   * @return country
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@jakarta.annotation.Nullable String country) {
    this.country = country;
  }


  public RetentionVerdict outcome(@jakarta.annotation.Nonnull OutcomeEnum outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OutcomeEnum getOutcome() {
    return outcome;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTCOME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutcome(@jakarta.annotation.Nonnull OutcomeEnum outcome) {
    this.outcome = outcome;
  }


  public RetentionVerdict policy(@jakarta.annotation.Nullable PolicyVersionRef policy) {
    this.policy = policy;
    return this;
  }

  /**
   * Get policy
   * @return policy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PolicyVersionRef getPolicy() {
    return policy;
  }


  @JsonProperty(value = JSON_PROPERTY_POLICY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicy(@jakarta.annotation.Nullable PolicyVersionRef policy) {
    this.policy = policy;
  }


  public RetentionVerdict candidates(@jakarta.annotation.Nullable List<PolicyVersionRef> candidates) {
    this.candidates = candidates;
    return this;
  }

  public RetentionVerdict addCandidatesItem(PolicyVersionRef candidatesItem) {
    if (this.candidates == null) {
      this.candidates = new ArrayList<>();
    }
    this.candidates.add(candidatesItem);
    return this;
  }

  /**
   * For &#x60;CONFLICTED&#x60;, the policies that disagree.
   * @return candidates
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CANDIDATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PolicyVersionRef> getCandidates() {
    return candidates;
  }


  @JsonProperty(value = JSON_PROPERTY_CANDIDATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCandidates(@jakarta.annotation.Nullable List<PolicyVersionRef> candidates) {
    this.candidates = candidates;
  }


  public RetentionVerdict retainUntil(@jakarta.annotation.Nullable String retainUntil) {
    this.retainUntil = retainUntil;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return retainUntil
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETAIN_UNTIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRetainUntil() {
    return retainUntil;
  }


  @JsonProperty(value = JSON_PROPERTY_RETAIN_UNTIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetainUntil(@jakarta.annotation.Nullable String retainUntil) {
    this.retainUntil = retainUntil;
  }


  public RetentionVerdict holds(@jakarta.annotation.Nullable List<UUID> holds) {
    this.holds = holds;
    return this;
  }

  public RetentionVerdict addHoldsItem(UUID holdsItem) {
    if (this.holds == null) {
      this.holds = new ArrayList<>();
    }
    this.holds.add(holdsItem);
    return this;
  }

  /**
   * The active holds that scope the record.
   * @return holds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<UUID> getHolds() {
    return holds;
  }


  @JsonProperty(value = JSON_PROPERTY_HOLDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHolds(@jakarta.annotation.Nullable List<UUID> holds) {
    this.holds = holds;
  }


  public RetentionVerdict detail(@jakarta.annotation.Nullable String detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Why a record is &#x60;NO_POLICY&#x60; or &#x60;CONFLICTED&#x60;.
   * @return detail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetail(@jakarta.annotation.Nullable String detail) {
    this.detail = detail;
  }


  public RetentionVerdict evaluatedAt(@jakarta.annotation.Nonnull String evaluatedAt) {
    this.evaluatedAt = evaluatedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return evaluatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVALUATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEvaluatedAt() {
    return evaluatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EVALUATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvaluatedAt(@jakarta.annotation.Nonnull String evaluatedAt) {
    this.evaluatedAt = evaluatedAt;
  }


  /**
   * Return true if this RetentionVerdict object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetentionVerdict retentionVerdict = (RetentionVerdict) o;
    return Objects.equals(this.decisionId, retentionVerdict.decisionId) &&
        Objects.equals(this.recordClass, retentionVerdict.recordClass) &&
        Objects.equals(this.country, retentionVerdict.country) &&
        Objects.equals(this.outcome, retentionVerdict.outcome) &&
        Objects.equals(this.policy, retentionVerdict.policy) &&
        Objects.equals(this.candidates, retentionVerdict.candidates) &&
        Objects.equals(this.retainUntil, retentionVerdict.retainUntil) &&
        Objects.equals(this.holds, retentionVerdict.holds) &&
        Objects.equals(this.detail, retentionVerdict.detail) &&
        Objects.equals(this.evaluatedAt, retentionVerdict.evaluatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(decisionId, recordClass, country, outcome, policy, candidates, retainUntil, holds, detail, evaluatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetentionVerdict {\n");
    sb.append("    decisionId: ").append(toIndentedString(decisionId)).append("\n");
    sb.append("    recordClass: ").append(toIndentedString(recordClass)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    candidates: ").append(toIndentedString(candidates)).append("\n");
    sb.append("    retainUntil: ").append(toIndentedString(retainUntil)).append("\n");
    sb.append("    holds: ").append(toIndentedString(holds)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    evaluatedAt: ").append(toIndentedString(evaluatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

