/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SealVerification
 */
@JsonPropertyOrder({
  SealVerification.JSON_PROPERTY_SEAL_ID,
  SealVerification.JSON_PROPERTY_VERDICT,
  SealVerification.JSON_PROPERTY_KEY_ID,
  SealVerification.JSON_PROPERTY_LEAF_COUNT,
  SealVerification.JSON_PROPERTY_SIGNED_ROOT,
  SealVerification.JSON_PROPERTY_RECOMPUTED_ROOT,
  SealVerification.JSON_PROPERTY_DETAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class SealVerification {
  public static final String JSON_PROPERTY_SEAL_ID = "sealId";
  @jakarta.annotation.Nonnull
  private UUID sealId;

  /**
   * Gets or Sets verdict
   */
  public enum VerdictEnum {
    VALID(String.valueOf("VALID")),
    
    SIGNATURE_INVALID(String.valueOf("SIGNATURE_INVALID")),
    
    RECORD_MISMATCH(String.valueOf("RECORD_MISMATCH")),
    
    ROOT_MISMATCH(String.valueOf("ROOT_MISMATCH")),
    
    EVIDENCE_MISSING(String.valueOf("EVIDENCE_MISSING")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    VerdictEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerdictEnum fromValue(String value) {
      for (VerdictEnum b : VerdictEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_VERDICT = "verdict";
  @jakarta.annotation.Nonnull
  private VerdictEnum verdict;

  public static final String JSON_PROPERTY_KEY_ID = "keyId";
  @jakarta.annotation.Nonnull
  private String keyId;

  public static final String JSON_PROPERTY_LEAF_COUNT = "leafCount";
  @jakarta.annotation.Nonnull
  private Integer leafCount;

  public static final String JSON_PROPERTY_SIGNED_ROOT = "signedRoot";
  @jakarta.annotation.Nonnull
  private String signedRoot;

  public static final String JSON_PROPERTY_RECOMPUTED_ROOT = "recomputedRoot";
  @jakarta.annotation.Nullable
  private String recomputedRoot;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  @jakarta.annotation.Nullable
  private String detail;

  public SealVerification() { 
  }

  public SealVerification sealId(@jakarta.annotation.Nonnull UUID sealId) {
    this.sealId = sealId;
    return this;
  }

  /**
   * A period seal. A UUIDv7 in lowercase canonical form.
   * @return sealId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getSealId() {
    return sealId;
  }


  @JsonProperty(value = JSON_PROPERTY_SEAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSealId(@jakarta.annotation.Nonnull UUID sealId) {
    this.sealId = sealId;
  }


  public SealVerification verdict(@jakarta.annotation.Nonnull VerdictEnum verdict) {
    this.verdict = verdict;
    return this;
  }

  /**
   * Get verdict
   * @return verdict
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERDICT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public VerdictEnum getVerdict() {
    return verdict;
  }


  @JsonProperty(value = JSON_PROPERTY_VERDICT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerdict(@jakarta.annotation.Nonnull VerdictEnum verdict) {
    this.verdict = verdict;
  }


  public SealVerification keyId(@jakarta.annotation.Nonnull String keyId) {
    this.keyId = keyId;
    return this;
  }

  /**
   * Get keyId
   * @return keyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKeyId() {
    return keyId;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyId(@jakarta.annotation.Nonnull String keyId) {
    this.keyId = keyId;
  }


  public SealVerification leafCount(@jakarta.annotation.Nonnull Integer leafCount) {
    this.leafCount = leafCount;
    return this;
  }

  /**
   * Get leafCount
   * @return leafCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEAF_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLeafCount() {
    return leafCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LEAF_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLeafCount(@jakarta.annotation.Nonnull Integer leafCount) {
    this.leafCount = leafCount;
  }


  public SealVerification signedRoot(@jakarta.annotation.Nonnull String signedRoot) {
    this.signedRoot = signedRoot;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return signedRoot
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNED_ROOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSignedRoot() {
    return signedRoot;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_ROOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedRoot(@jakarta.annotation.Nonnull String signedRoot) {
    this.signedRoot = signedRoot;
  }


  public SealVerification recomputedRoot(@jakarta.annotation.Nullable String recomputedRoot) {
    this.recomputedRoot = recomputedRoot;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return recomputedRoot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECOMPUTED_ROOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRecomputedRoot() {
    return recomputedRoot;
  }


  @JsonProperty(value = JSON_PROPERTY_RECOMPUTED_ROOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecomputedRoot(@jakarta.annotation.Nullable String recomputedRoot) {
    this.recomputedRoot = recomputedRoot;
  }


  public SealVerification detail(@jakarta.annotation.Nullable String detail) {
    this.detail = detail;
    return this;
  }

  /**
   * What failed, for the operator. Absent when VALID.
   * @return detail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetail(@jakarta.annotation.Nullable String detail) {
    this.detail = detail;
  }


  /**
   * Return true if this SealVerification object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SealVerification sealVerification = (SealVerification) o;
    return Objects.equals(this.sealId, sealVerification.sealId) &&
        Objects.equals(this.verdict, sealVerification.verdict) &&
        Objects.equals(this.keyId, sealVerification.keyId) &&
        Objects.equals(this.leafCount, sealVerification.leafCount) &&
        Objects.equals(this.signedRoot, sealVerification.signedRoot) &&
        Objects.equals(this.recomputedRoot, sealVerification.recomputedRoot) &&
        Objects.equals(this.detail, sealVerification.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sealId, verdict, keyId, leafCount, signedRoot, recomputedRoot, detail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SealVerification {\n");
    sb.append("    sealId: ").append(toIndentedString(sealId)).append("\n");
    sb.append("    verdict: ").append(toIndentedString(verdict)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    leafCount: ").append(toIndentedString(leafCount)).append("\n");
    sb.append("    signedRoot: ").append(toIndentedString(signedRoot)).append("\n");
    sb.append("    recomputedRoot: ").append(toIndentedString(recomputedRoot)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

