/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * A signed statement that the decisions recorded in &#x60;[periodStart, periodEnd)&#x60; were exactly these.
 */
@JsonPropertyOrder({
  Seal.JSON_PROPERTY_ID,
  Seal.JSON_PROPERTY_PERIOD_START,
  Seal.JSON_PROPERTY_PERIOD_END,
  Seal.JSON_PROPERTY_LEAF_COUNT,
  Seal.JSON_PROPERTY_MERKLE_ROOT,
  Seal.JSON_PROPERTY_KEY_ID,
  Seal.JSON_PROPERTY_CELL,
  Seal.JSON_PROPERTY_SEALED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Seal {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PERIOD_START = "periodStart";
  @jakarta.annotation.Nonnull
  private String periodStart;

  public static final String JSON_PROPERTY_PERIOD_END = "periodEnd";
  @jakarta.annotation.Nonnull
  private String periodEnd;

  public static final String JSON_PROPERTY_LEAF_COUNT = "leafCount";
  @jakarta.annotation.Nonnull
  private Integer leafCount;

  public static final String JSON_PROPERTY_MERKLE_ROOT = "merkleRoot";
  @jakarta.annotation.Nonnull
  private String merkleRoot;

  public static final String JSON_PROPERTY_KEY_ID = "keyId";
  @jakarta.annotation.Nonnull
  private String keyId;

  public static final String JSON_PROPERTY_CELL = "cell";
  @jakarta.annotation.Nonnull
  private String cell;

  public static final String JSON_PROPERTY_SEALED_AT = "sealedAt";
  @jakarta.annotation.Nonnull
  private String sealedAt;

  public Seal() { 
  }

  public Seal id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * A period seal. A UUIDv7 in lowercase canonical form.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public Seal periodStart(@jakarta.annotation.Nonnull String periodStart) {
    this.periodStart = periodStart;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return periodStart
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPeriodStart() {
    return periodStart;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriodStart(@jakarta.annotation.Nonnull String periodStart) {
    this.periodStart = periodStart;
  }


  public Seal periodEnd(@jakarta.annotation.Nonnull String periodEnd) {
    this.periodEnd = periodEnd;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return periodEnd
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPeriodEnd() {
    return periodEnd;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriodEnd(@jakarta.annotation.Nonnull String periodEnd) {
    this.periodEnd = periodEnd;
  }


  public Seal leafCount(@jakarta.annotation.Nonnull Integer leafCount) {
    this.leafCount = leafCount;
    return this;
  }

  /**
   * Get leafCount
   * minimum: 0
   * @return leafCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEAF_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getLeafCount() {
    return leafCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LEAF_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLeafCount(@jakarta.annotation.Nonnull Integer leafCount) {
    this.leafCount = leafCount;
  }


  public Seal merkleRoot(@jakarta.annotation.Nonnull String merkleRoot) {
    this.merkleRoot = merkleRoot;
    return this;
  }

  /**
   * A canonical digest: SHA-256 over the canonical bytes, lowercase hex, carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is not decoration — a future &#x60;zt2:&#x60; digest of the same document is a different digest, and comparing the two without it would be wrong. 
   * @return merkleRoot
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MERKLE_ROOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMerkleRoot() {
    return merkleRoot;
  }


  @JsonProperty(value = JSON_PROPERTY_MERKLE_ROOT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerkleRoot(@jakarta.annotation.Nonnull String merkleRoot) {
    this.merkleRoot = merkleRoot;
  }


  public Seal keyId(@jakarta.annotation.Nonnull String keyId) {
    this.keyId = keyId;
    return this;
  }

  /**
   * Get keyId
   * @return keyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKeyId() {
    return keyId;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeyId(@jakarta.annotation.Nonnull String keyId) {
    this.keyId = keyId;
  }


  public Seal cell(@jakarta.annotation.Nonnull String cell) {
    this.cell = cell;
    return this;
  }

  /**
   * Get cell
   * @return cell
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CELL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCell() {
    return cell;
  }


  @JsonProperty(value = JSON_PROPERTY_CELL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCell(@jakarta.annotation.Nonnull String cell) {
    this.cell = cell;
  }


  public Seal sealedAt(@jakarta.annotation.Nonnull String sealedAt) {
    this.sealedAt = sealedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return sealedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEALED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSealedAt() {
    return sealedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SEALED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSealedAt(@jakarta.annotation.Nonnull String sealedAt) {
    this.sealedAt = sealedAt;
  }


  /**
   * Return true if this Seal object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Seal seal = (Seal) o;
    return Objects.equals(this.id, seal.id) &&
        Objects.equals(this.periodStart, seal.periodStart) &&
        Objects.equals(this.periodEnd, seal.periodEnd) &&
        Objects.equals(this.leafCount, seal.leafCount) &&
        Objects.equals(this.merkleRoot, seal.merkleRoot) &&
        Objects.equals(this.keyId, seal.keyId) &&
        Objects.equals(this.cell, seal.cell) &&
        Objects.equals(this.sealedAt, seal.sealedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, periodStart, periodEnd, leafCount, merkleRoot, keyId, cell, sealedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Seal {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    periodStart: ").append(toIndentedString(periodStart)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("    leafCount: ").append(toIndentedString(leafCount)).append("\n");
    sb.append("    merkleRoot: ").append(toIndentedString(merkleRoot)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    cell: ").append(toIndentedString(cell)).append("\n");
    sb.append("    sealedAt: ").append(toIndentedString(sealedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

