/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.CloseManifestDocument;
import com.zoikotax.sdk.model.PeriodEvent;
import com.zoikotax.sdk.model.PeriodState;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SubledgerPeriod
 */
@JsonPropertyOrder({
  SubledgerPeriod.JSON_PROPERTY_PERIOD,
  SubledgerPeriod.JSON_PROPERTY_LEGAL_ENTITY_ID,
  SubledgerPeriod.JSON_PROPERTY_STATE,
  SubledgerPeriod.JSON_PROPERTY_HISTORY,
  SubledgerPeriod.JSON_PROPERTY_MANIFEST,
  SubledgerPeriod.JSON_PROPERTY_INTACT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class SubledgerPeriod {
  public static final String JSON_PROPERTY_PERIOD = "period";
  @jakarta.annotation.Nonnull
  private String period;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_ID = "legalEntityId";
  @jakarta.annotation.Nonnull
  private UUID legalEntityId;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nonnull
  private PeriodState state;

  public static final String JSON_PROPERTY_HISTORY = "history";
  @jakarta.annotation.Nonnull
  private List<PeriodEvent> history;

  public static final String JSON_PROPERTY_MANIFEST = "manifest";
  @jakarta.annotation.Nullable
  private CloseManifestDocument manifest;

  public static final String JSON_PROPERTY_INTACT = "intact";
  @jakarta.annotation.Nullable
  private Boolean intact;

  public SubledgerPeriod() { 
  }

  public SubledgerPeriod period(@jakarta.annotation.Nonnull String period) {
    this.period = period;
    return this;
  }

  /**
   * A subledger legal period, a month.
   * @return period
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPeriod() {
    return period;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriod(@jakarta.annotation.Nonnull String period) {
    this.period = period;
  }


  public SubledgerPeriod legalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
    return this;
  }

  /**
   * A legal entity within the tenant (ZTAX-OBL-REQ-0018). A UUID in lowercase canonical form.
   * @return legalEntityId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getLegalEntityId() {
    return legalEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_ENTITY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalEntityId(@jakarta.annotation.Nonnull UUID legalEntityId) {
    this.legalEntityId = legalEntityId;
  }


  public SubledgerPeriod state(@jakarta.annotation.Nonnull PeriodState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PeriodState getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@jakarta.annotation.Nonnull PeriodState state) {
    this.state = state;
  }


  public SubledgerPeriod history(@jakarta.annotation.Nonnull List<PeriodEvent> history) {
    this.history = history;
    return this;
  }

  public SubledgerPeriod addHistoryItem(PeriodEvent historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<>();
    }
    this.history.add(historyItem);
    return this;
  }

  /**
   * Get history
   * @return history
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<PeriodEvent> getHistory() {
    return history;
  }


  @JsonProperty(value = JSON_PROPERTY_HISTORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHistory(@jakarta.annotation.Nonnull List<PeriodEvent> history) {
    this.history = history;
  }


  public SubledgerPeriod manifest(@jakarta.annotation.Nullable CloseManifestDocument manifest) {
    this.manifest = manifest;
    return this;
  }

  /**
   * Get manifest
   * @return manifest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANIFEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CloseManifestDocument getManifest() {
    return manifest;
  }


  @JsonProperty(value = JSON_PROPERTY_MANIFEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManifest(@jakarta.annotation.Nullable CloseManifestDocument manifest) {
    this.manifest = manifest;
  }


  public SubledgerPeriod intact(@jakarta.annotation.Nullable Boolean intact) {
    this.intact = intact;
    return this;
  }

  /**
   * Whether the period&#39;s journals and balances today are exactly the ones its latest manifest sealed. Absent until the period is first hard-closed.
   * @return intact
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIntact() {
    return intact;
  }


  @JsonProperty(value = JSON_PROPERTY_INTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntact(@jakarta.annotation.Nullable Boolean intact) {
    this.intact = intact;
  }


  /**
   * Return true if this SubledgerPeriod object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubledgerPeriod subledgerPeriod = (SubledgerPeriod) o;
    return Objects.equals(this.period, subledgerPeriod.period) &&
        Objects.equals(this.legalEntityId, subledgerPeriod.legalEntityId) &&
        Objects.equals(this.state, subledgerPeriod.state) &&
        Objects.equals(this.history, subledgerPeriod.history) &&
        Objects.equals(this.manifest, subledgerPeriod.manifest) &&
        Objects.equals(this.intact, subledgerPeriod.intact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(period, legalEntityId, state, history, manifest, intact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubledgerPeriod {\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    legalEntityId: ").append(toIndentedString(legalEntityId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("    intact: ").append(toIndentedString(intact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

