/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication and tenant administration. The determination surface named in `ZTAX-INT-001` — quotes, transaction commit, adjust, refund, decisions, replay, classifications, obligations, batches and jobs — is not here yet and is added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  This version of the surface carries no fiscal amounts. The rule is stated here because it governs every addition to it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zoikotax.sdk.model.TenantStatus;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Tenant
 */
@JsonPropertyOrder({
  Tenant.JSON_PROPERTY_ID,
  Tenant.JSON_PROPERTY_SLUG,
  Tenant.JSON_PROPERTY_DISPLAY_NAME,
  Tenant.JSON_PROPERTY_RESIDENCY_REGION,
  Tenant.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Tenant {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @jakarta.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @jakarta.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_RESIDENCY_REGION = "residencyRegion";
  @jakarta.annotation.Nonnull
  private String residencyRegion;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private TenantStatus status;

  public Tenant() { 
  }

  public Tenant id(@jakarta.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * A tenant identifier (ADR-0012). Prefixed, sortable, never recycled.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }


  public Tenant slug(@jakarta.annotation.Nonnull String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * The stable, human-usable name a client signs in with.
   * @return slug
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@jakarta.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public Tenant displayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }


  public Tenant residencyRegion(@jakarta.annotation.Nonnull String residencyRegion) {
    this.residencyRegion = residencyRegion;
    return this;
  }

  /**
   * The region whose cell holds this tenant&#39;s data. It never leaves it, which is why this is reported rather than inferred. 
   * @return residencyRegion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESIDENCY_REGION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResidencyRegion() {
    return residencyRegion;
  }


  @JsonProperty(value = JSON_PROPERTY_RESIDENCY_REGION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResidencyRegion(@jakarta.annotation.Nonnull String residencyRegion) {
    this.residencyRegion = residencyRegion;
  }


  public Tenant status(@jakarta.annotation.Nonnull TenantStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TenantStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull TenantStatus status) {
    this.status = status;
  }


  /**
   * Return true if this Tenant object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tenant tenant = (Tenant) o;
    return Objects.equals(this.id, tenant.id) &&
        Objects.equals(this.slug, tenant.slug) &&
        Objects.equals(this.displayName, tenant.displayName) &&
        Objects.equals(this.residencyRegion, tenant.residencyRegion) &&
        Objects.equals(this.status, tenant.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, displayName, residencyRegion, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tenant {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    residencyRegion: ").append(toIndentedString(residencyRegion)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

