/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication and tenant administration. The determination surface named in `ZTAX-INT-001` — quotes, transaction commit, adjust, refund, decisions, replay, classifications, obligations, batches and jobs — is not here yet and is added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  This version of the surface carries no fiscal amounts. The rule is stated here because it governs every addition to it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * The seven release-train versions. Together they name the exact combination of code, content, models, adapters, infrastructure, schemas and migrations that produced a response — which is what makes a decision replayable years later. 
 */
@JsonPropertyOrder({
  Trains.JSON_PROPERTY_APP,
  Trains.JSON_PROPERTY_CONTENT,
  Trains.JSON_PROPERTY_AI,
  Trains.JSON_PROPERTY_ADAPTER,
  Trains.JSON_PROPERTY_INFRA,
  Trains.JSON_PROPERTY_SCHEMA,
  Trains.JSON_PROPERTY_MIGRATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class Trains {
  public static final String JSON_PROPERTY_APP = "app";
  @jakarta.annotation.Nonnull
  private String app;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @jakarta.annotation.Nonnull
  private String content;

  public static final String JSON_PROPERTY_AI = "ai";
  @jakarta.annotation.Nonnull
  private String ai;

  public static final String JSON_PROPERTY_ADAPTER = "adapter";
  @jakarta.annotation.Nonnull
  private String adapter;

  public static final String JSON_PROPERTY_INFRA = "infra";
  @jakarta.annotation.Nonnull
  private String infra;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @jakarta.annotation.Nonnull
  private String schema;

  public static final String JSON_PROPERTY_MIGRATION = "migration";
  @jakarta.annotation.Nonnull
  private String migration;

  public Trains() { 
  }

  public Trains app(@jakarta.annotation.Nonnull String app) {
    this.app = app;
    return this;
  }

  /**
   * Get app
   * @return app
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getApp() {
    return app;
  }


  @JsonProperty(value = JSON_PROPERTY_APP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApp(@jakarta.annotation.Nonnull String app) {
    this.app = app;
  }


  public Trains content(@jakarta.annotation.Nonnull String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@jakarta.annotation.Nonnull String content) {
    this.content = content;
  }


  public Trains ai(@jakarta.annotation.Nonnull String ai) {
    this.ai = ai;
    return this;
  }

  /**
   * Get ai
   * @return ai
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAi() {
    return ai;
  }


  @JsonProperty(value = JSON_PROPERTY_AI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAi(@jakarta.annotation.Nonnull String ai) {
    this.ai = ai;
  }


  public Trains adapter(@jakarta.annotation.Nonnull String adapter) {
    this.adapter = adapter;
    return this;
  }

  /**
   * Get adapter
   * @return adapter
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADAPTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAdapter() {
    return adapter;
  }


  @JsonProperty(value = JSON_PROPERTY_ADAPTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdapter(@jakarta.annotation.Nonnull String adapter) {
    this.adapter = adapter;
  }


  public Trains infra(@jakarta.annotation.Nonnull String infra) {
    this.infra = infra;
    return this;
  }

  /**
   * Get infra
   * @return infra
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INFRA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getInfra() {
    return infra;
  }


  @JsonProperty(value = JSON_PROPERTY_INFRA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInfra(@jakarta.annotation.Nonnull String infra) {
    this.infra = infra;
  }


  public Trains schema(@jakarta.annotation.Nonnull String schema) {
    this.schema = schema;
    return this;
  }

  /**
   * Get schema
   * @return schema
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSchema(@jakarta.annotation.Nonnull String schema) {
    this.schema = schema;
  }


  public Trains migration(@jakarta.annotation.Nonnull String migration) {
    this.migration = migration;
    return this;
  }

  /**
   * Get migration
   * @return migration
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MIGRATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMigration() {
    return migration;
  }


  @JsonProperty(value = JSON_PROPERTY_MIGRATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMigration(@jakarta.annotation.Nonnull String migration) {
    this.migration = migration;
  }


  /**
   * Return true if this Trains object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trains trains = (Trains) o;
    return Objects.equals(this.app, trains.app) &&
        Objects.equals(this.content, trains.content) &&
        Objects.equals(this.ai, trains.ai) &&
        Objects.equals(this.adapter, trains.adapter) &&
        Objects.equals(this.infra, trains.infra) &&
        Objects.equals(this.schema, trains.schema) &&
        Objects.equals(this.migration, trains.migration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, content, ai, adapter, infra, schema, migration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trains {\n");
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    ai: ").append(toIndentedString(ai)).append("\n");
    sb.append("    adapter: ").append(toIndentedString(adapter)).append("\n");
    sb.append("    infra: ").append(toIndentedString(infra)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    migration: ").append(toIndentedString(migration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

