/*
 * ZoikoTax
 * This is the `/v1` surface a ZoikoTax regional cell serves today: discovery, authentication, tenant administration, and the first part of the determination surface named in `ZTAX-INT-001` — quotes, transaction commit, decisions and replay. Adjust, refund, classifications, obligations, batches and jobs are added by addition under the same major version (ADR-0010 §2.6).  **No authoritative fiscal output is permitted before A4.** A client discovers whether this deployment may produce one from `GET /v1/capabilities`, which reports `authoritative`, never from a release note. A deployment reporting `authoritative: false` produces advisory figures that must not be filed.  ## Errors  Every error is an RFC 9457 Problem Details document with `Content-Type: application/problem+json` (ADR-0016). Two fields matter more than the status code:  - `ztx_reason_code` is from a closed, registered vocabulary. It means the   same thing in an error, in a decision and in evidence, and it is what a   client branches on. Never match on `title` or `detail`; both may be   reworded. - `ztx_retryable` states whether retrying the request unchanged could   succeed. It is a property of the error rather than something to infer from   the status, so a client does not have to guess.  The full reason-code vocabulary this deployment can emit is reported by `GET /v1/capabilities`.  ## Fiscal amounts  Every fiscal amount in this API is a JSON **string** in canonical decimal form, such as `\"12.50\"` — never a JSON number (ADR-0010 §2.9). Trailing zeros are significant: `\"1.50\"` and `\"1.5\"` are different assertions about precision. Do not parse one into a binary float; `JSON.parse` in a browser does exactly that and is the reason this rule exists.  The same holds for rates and quantities, and for every value a determination emits. The `Decimal` schema is the one definition of the form. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zoikotax.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WebhookAttempt
 */
@JsonPropertyOrder({
  WebhookAttempt.JSON_PROPERTY_ATTEMPT,
  WebhookAttempt.JSON_PROPERTY_STARTED_AT,
  WebhookAttempt.JSON_PROPERTY_DURATION_MS,
  WebhookAttempt.JSON_PROPERTY_STATUS_CODE,
  WebhookAttempt.JSON_PROPERTY_ERROR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class WebhookAttempt {
  public static final String JSON_PROPERTY_ATTEMPT = "attempt";
  @jakarta.annotation.Nonnull
  private Integer attempt;

  public static final String JSON_PROPERTY_STARTED_AT = "startedAt";
  @jakarta.annotation.Nonnull
  private String startedAt;

  public static final String JSON_PROPERTY_DURATION_MS = "durationMs";
  @jakarta.annotation.Nonnull
  private Integer durationMs;

  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
  @jakarta.annotation.Nullable
  private Integer statusCode;

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nullable
  private String error;

  public WebhookAttempt() { 
  }

  public WebhookAttempt attempt(@jakarta.annotation.Nonnull Integer attempt) {
    this.attempt = attempt;
    return this;
  }

  /**
   * Get attempt
   * minimum: 1
   * @return attempt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getAttempt() {
    return attempt;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTEMPT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttempt(@jakarta.annotation.Nonnull Integer attempt) {
    this.attempt = attempt;
  }


  public WebhookAttempt startedAt(@jakarta.annotation.Nonnull String startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * RFC 3339 UTC with exactly six fractional digits and a literal &#x60;Z&#x60; (ADR-0011 §2.1 P2). No offsets and no variable precision, because two encodings of one instant must not produce two digests. 
   * @return startedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STARTED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStartedAt() {
    return startedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartedAt(@jakarta.annotation.Nonnull String startedAt) {
    this.startedAt = startedAt;
  }


  public WebhookAttempt durationMs(@jakarta.annotation.Nonnull Integer durationMs) {
    this.durationMs = durationMs;
    return this;
  }

  /**
   * Get durationMs
   * minimum: 0
   * @return durationMs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DURATION_MS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDurationMs() {
    return durationMs;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION_MS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDurationMs(@jakarta.annotation.Nonnull Integer durationMs) {
    this.durationMs = durationMs;
  }


  public WebhookAttempt statusCode(@jakarta.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * The receiver&#39;s HTTP status. Absent when no response arrived.
   * @return statusCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getStatusCode() {
    return statusCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusCode(@jakarta.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
  }


  public WebhookAttempt error(@jakarta.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * The transport&#39;s error, when no 2xx arrived. Never the receiver&#39;s response body.
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = error;
  }


  /**
   * Return true if this WebhookAttempt object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookAttempt webhookAttempt = (WebhookAttempt) o;
    return Objects.equals(this.attempt, webhookAttempt.attempt) &&
        Objects.equals(this.startedAt, webhookAttempt.startedAt) &&
        Objects.equals(this.durationMs, webhookAttempt.durationMs) &&
        Objects.equals(this.statusCode, webhookAttempt.statusCode) &&
        Objects.equals(this.error, webhookAttempt.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attempt, startedAt, durationMs, statusCode, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookAttempt {\n");
    sb.append("    attempt: ").append(toIndentedString(attempt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

