"""ZoikoTax Governed Model Gateway.
 
The only path between the Go fiscal core and any model provider (ADR-0006
§2.1). Nothing in the estate calls a provider directly; network policy in the
regional cell denies Go workloads egress to provider endpoints, so this is
enforced by the network rather than by anyone remembering.
 
What is here today is the enforcement point — the part ADR-0006 §2.5 makes the
Gateway's reason for existing — and the decimal boundary of §2.3. What is not
here is the transport: gRPC service definitions are generated from
``contracts/schemas`` (ADR-0006 §2.2, ADR-0010 §2.1), and that pipeline opens in
W2 lane K. ``service.py`` marks the seam.
 
The ordering is deliberate rather than convenient. The governance logic is
testable with no transport, no provider and no model, and it is the half that
has to be right; the transport is plumbing that can be generated once the
contract exists. Building it the other way round produces a Gateway that can
carry a request before it can refuse one.
"""
 
from .ai_security_controls import (
    AISecurityError,
    AISecurityRefusal,
    FieldType,
    OutputSchema,
    OutputSchemaValidator,
    OutputValidationResult,
    TenantContext,
    TenantScopedIndex,
    TenantScopedSearchResult,
)
from .capacity import (
    CapacityError,
    CapacityLedger,
    FinOpsReport,
    QuotaPolicy,
    QuotaState,
    QuotaViolation,
    QuotaWindow,
)
from .change_intelligence import (
    AuthorityLevel,
    CandidateStatus,
    CandidateStatusRecord,
    ChangeCandidate,
    ChangeCandidateError,
    ChangeIntelligenceEngine,
    ChangeType,
    CorpusEntry,
    EffectiveDateEvidence,
)
from .classifier import (
    ClassificationError,
    ClassificationProposal,
    ClassificationRecord,
    Classifier,
)
from .decimal_wire import DecimalWireError, parse, render
from .drift import (
    BehaviorFingerprint,
    CanaryEvaluator,
    CanaryEvaluatorError,
    CanaryProbe,
    CanaryVerdict,
    CanaryVerdictReport,
    DriftDetector,
    DriftError,
    DriftReport,
    DriftStatus,
    FingerprintComparison,
    FingerprintError,
    FingerprintReport,
    InvocationSignal,
    ProbeResult,
    compare_fingerprints,
)
from .evaluation import (
    EvaluationError,
    EvaluationReport,
    EvaluationRule,
    EvaluationRuleset,
    EvaluationVerdict,
    Evaluator,
    RuleOutcome,
    RuleResult,
    evaluate,
)
from .evaluation_evidence import (
    EvaluationEvidenceError,
    EvaluationEvidenceRecord,
    GateVerdict,
)
from .evaluation_evidence import (
    build as build_evaluation_evidence,
)
from .evaluation_quality import (
    ComparisonOutcome,
    ComparisonReport,
    GoldCase,
    GoldSetError,
    GoldSetStore,
    MetricEngine,
    MetricEngineError,
    MetricReport,
    ModelComparator,
    PerClassMetric,
)
from .evaluation_runner import (
    CaseOutcome,
    CaseResult,
    EvaluationRunner,
    EvaluationRunnerError,
    RulesetCaseResult,
    RulesetRunReport,
    RunReport,
)
from .explanation import (
    CitationBundle,
    CitationResolutionError,
    CustomerExplanationService,
    DecisionTrace,
    ExplanationError,
    ExplanationResult,
    ExplanationSegment,
    TraceStep,
    build_explanation,
)
from .governance import (
    MAX_PERMITTED_AUTHORITY,
    GovernanceRefusedError,
    Refusal,
    UseCase,
    UseCaseRegistry,
    authorise,
)
from .human_review import (
    DecisionReasonCode,
    EvidencePanel,
    PromotedRecord,
    ReviewDecision,
    ReviewerProfile,
    ReviewError,
    ReviewItem,
    ReviewOutcome,
    ReviewPriority,
    ReviewQueue,
    ReviewStatus,
)
from .invocation_evidence import (
    GuardrailResult,
    InvocationEvidenceBuilder,
    InvocationEvidenceError,
    InvocationEvidenceRecord,
    InvocationOutcome,
    ToolCallRecord,
    UsageMetrics,
)
from .observability import (
    DEFAULT_AUDIT_BUFFER_CAPACITY,
    AuditBuffer,
    AuditEntry,
    AuditEventKind,
    ObservabilityError,
    ObservabilityPipeline,
    SignalFamily,
    TelemetrySignal,
    record_audit_entries,
    record_signals,
)
from .privacy_source_rights import (
    CustomerPolicy,
    DataSubjectCategory,
    LegalBasis,
    PrivacyRefusal,
    PrivacySourceRightsError,
    ProcessingActivity,
    ProcessingRole,
    ProviderRetentionPolicy,
    RightsDecision,
    RightsProfile,
    SourceClass,
    SourceRightsRecord,
    SourceUse,
    check_corpus_source,
    check_invocation_privacy,
    check_provider_retention,
    check_source_use,
)
from .production_registries import (
    AgentMemoryPolicy,
    AgentProfile,
    AgentProfileError,
    AIReleaseManifest,
    AIReleaseManifestError,
    DatasetProfile,
    DatasetProfileError,
    EvaluationProfile,
    EvaluationProfileError,
    ManifestRegistry,
    ManifestRegistryError,
    ManifestStatus,
    PromptProfile,
    PromptProfileError,
    build_manifest,
)
from .provenance import AuthorityOutcome, Provenance, RiskTier
from .release_lifecycle import (
    LifecycleError,
    LifecycleRecord,
    LifecycleState,
    ManifestLifecycle,
    TrafficAuthority,
    can_serve_production,
)
from .resilience import (
    DegradedMode,
    EdgePolicySnapshot,
    FailureKind,
    FallbackRouter,
    ModelRecord,
    ModelWeightRecord,
    ProviderRecord,
    ProviderRegistry,
    ResilienceError,
    RoutingOutcome,
    WeightScanStatus,
    authorise_edge,
)
from .tool_broker import (
    MAX_PERMITTED_ACTION_CLASS,
    ActionClass,
    AgentAudit,
    ToolBrokerRefusedError,
    ToolCatalog,
    ToolProfile,
    ToolProvenance,
    guarded,
)
from .tool_broker import (
    Refusal as ToolRefusal,
)
from .tool_broker import (
    authorise as authorise_tool,
)

__all__ = [
    "DEFAULT_AUDIT_BUFFER_CAPACITY",
    "MAX_PERMITTED_ACTION_CLASS",
    "MAX_PERMITTED_AUTHORITY",
    "AIReleaseManifest",
    "AIReleaseManifestError",
    "AISecurityError",
    "AISecurityRefusal",
    "ActionClass",
    "AgentAudit",
    "AgentMemoryPolicy",
    "AgentProfile",
    "AgentProfileError",
    "AuditBuffer",
    "AuditEntry",
    "AuditEventKind",
    "AuthorityLevel",
    "AuthorityOutcome",
    "BehaviorFingerprint",
    "CanaryEvaluator",
    "CanaryEvaluatorError",
    "CanaryProbe",
    "CanaryVerdict",
    "CanaryVerdictReport",
    "CandidateStatus",
    "CandidateStatusRecord",
    "CapacityError",
    "CapacityLedger",
    "CaseOutcome",
    "CaseResult",
    "ChangeCandidate",
    "ChangeCandidateError",
    "ChangeIntelligenceEngine",
    "ChangeType",
    "CitationBundle",
    "CitationResolutionError",
    "ClassificationError",
    "ClassificationProposal",
    "ClassificationRecord",
    "Classifier",
    "ComparisonOutcome",
    "ComparisonReport",
    "CorpusEntry",
    "CustomerExplanationService",
    "CustomerPolicy",
    "DataSubjectCategory",
    "DatasetProfile",
    "DatasetProfileError",
    "DecimalWireError",
    "DecisionReasonCode",
    "DecisionTrace",
    "DegradedMode",
    "DriftDetector",
    "DriftError",
    "DriftReport",
    "DriftStatus",
    "EdgePolicySnapshot",
    "EffectiveDateEvidence",
    "EvaluationError",
    "EvaluationEvidenceError",
    "EvaluationEvidenceRecord",
    "EvaluationProfile",
    "EvaluationProfileError",
    "EvaluationReport",
    "EvaluationRule",
    "EvaluationRuleset",
    "EvaluationRunner",
    "EvaluationRunnerError",
    "EvaluationVerdict",
    "Evaluator",
    "EvidencePanel",
    "ExplanationError",
    "ExplanationResult",
    "ExplanationSegment",
    "FailureKind",
    "FallbackRouter",
    "FieldType",
    "FinOpsReport",
    "FingerprintComparison",
    "FingerprintError",
    "FingerprintReport",
    "GateVerdict",
    "GoldCase",
    "GoldSetError",
    "GoldSetStore",
    "GovernanceRefusedError",
    "GuardrailResult",
    "InvocationEvidenceBuilder",
    "InvocationEvidenceError",
    "InvocationEvidenceRecord",
    "InvocationOutcome",
    "InvocationSignal",
    "LegalBasis",
    "LifecycleError",
    "LifecycleRecord",
    "LifecycleState",
    "ManifestLifecycle",
    "ManifestRegistry",
    "ManifestRegistryError",
    "ManifestStatus",
    "MetricEngine",
    "MetricEngineError",
    "MetricReport",
    "ModelComparator",
    "ModelRecord",
    "ModelWeightRecord",
    "ObservabilityError",
    "ObservabilityPipeline",
    "OutputSchema",
    "OutputSchemaValidator",
    "OutputValidationResult",
    "PerClassMetric",
    "PrivacyRefusal",
    "PrivacySourceRightsError",
    "ProbeResult",
    "ProcessingActivity",
    "ProcessingRole",
    "PromotedRecord",
    "PromptProfile",
    "PromptProfileError",
    "Provenance",
    "ProviderRecord",
    "ProviderRegistry",
    "ProviderRetentionPolicy",
    "QuotaPolicy",
    "QuotaState",
    "QuotaViolation",
    "QuotaWindow",
    "Refusal",
    "ResilienceError",
    "ReviewDecision",
    "ReviewError",
    "ReviewItem",
    "ReviewOutcome",
    "ReviewPriority",
    "ReviewQueue",
    "ReviewStatus",
    "ReviewerProfile",
    "RightsDecision",
    "RightsProfile",
    "RiskTier",
    "RoutingOutcome",
    "RuleOutcome",
    "RuleResult",
    "RulesetCaseResult",
    "RulesetRunReport",
    "RunReport",
    "SignalFamily",
    "SourceClass",
    "SourceRightsRecord",
    "SourceUse",
    "TelemetrySignal",
    "TenantContext",
    "TenantScopedIndex",
    "TenantScopedSearchResult",
    "ToolBrokerRefusedError",
    "ToolCallRecord",
    "ToolCatalog",
    "ToolProfile",
    "ToolProvenance",
    "ToolRefusal",
    "TraceStep",
    "TrafficAuthority",
    "UsageMetrics",
    "UseCase",
    "UseCaseRegistry",
    "WeightScanStatus",
    "authorise",
    "authorise_edge",
    "authorise_tool",
    "build_evaluation_evidence",
    "build_explanation",
    "build_manifest",
    "can_serve_production",
    "check_corpus_source",
    "check_invocation_privacy",
    "check_provider_retention",
    "check_source_use",
    "compare_fingerprints",
    "evaluate",
    "guarded",
    "parse",
    "record_audit_entries",
    "record_signals",
    "render",
]