// Code generated by 'go test'. DO NOT EDIT.

// This fixture is a guarded package's generated file. The rules constrain what
// someone writes in the domain; the file `go test` generates to run a guarded
// package's own tests declares a *testing.M, which structurally contains a
// float, and reporting it would make every domain package with a test suite a
// finding. Nothing here is a finding.
package guarded

type generatedRatio float64

var generatedFactor float64

type generatedLine struct {
	Weight float64
}

func generatedTotal() float64 {
	return 0
}
