/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report this deployment's effective capability
         * @description Effective capability, not entitlement: the intersection of content
         *     state, security, QA and commercial entitlement (ADR-0010 §2.6).
         *
         *     Unauthenticated, because a client needs to know whether a cell can serve
         *     it before it has a session, and because an integration diagnosing a
         *     problem should not need a credential to report which cell and which
         *     content bundle it reached.
         *
         *     `content` is absent in a cell with no bundle loaded, which is a
         *     legitimate deployment before A4. Absent rather than null: "no content"
         *     and "content with no identity" are different facts (ADR-0011 P3).
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a session
         * @description Exchanges a tenant slug, an email address and a password for an opaque
         *     session cookie.
         *
         *     The response carries **no token**. The session identifier is in a
         *     `__Host-`-prefixed, `HttpOnly`, `SameSite=Strict` cookie that JavaScript
         *     cannot read, which is why the browser client has nothing to store and
         *     nothing to leak (ADR-0019 C8, ADR-0020).
         *
         *     A failure does not distinguish an unknown subject from a wrong password.
         *     The difference is an account-enumeration oracle and a caller can do
         *     nothing with it, so both are `INVALID_CREDENTIALS`.
         */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Revokes this session server-side and clears the cookie. The session is
         *     revoked rather than forgotten, so it appears in
         *     `GET /v1/admin/sessions` with `revoked: true` — a session that vanished
         *     would leave nothing for an audit to look at.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I, and until when
         * @description The only way a client learns its own identity. Nothing about the session
         *     is readable in the browser, so a client calls this on load rather than
         *     decoding a token (ADR-0019 C8).
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current subject's password
         * @description Verifies the current password and replaces it.
         *
         *     **Every session for this subject is revoked, including this one.** A
         *     password change is the action taken when a credential is believed
         *     compromised, and leaving other sessions alive would defeat it. The
         *     client is signed out and must sign in again.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated subject's tenant
         * @description Requires a session but no particular role: every member of a tenant may
         *     see which tenant they are in, its residency region and whether it is
         *     suspended.
         */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tenant's users
         * @description Readable by `ADMIN`, `ANALYST` and `AUDITOR`.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user
         * @description `ADMIN` only. A user created without a password is `INVITED` and cannot
         *     sign in until one is set.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable or disable a user
         * @description `ADMIN` only. Disabling a user revokes their sessions: an account whose
         *     access has been withdrawn and whose session still works is an account
         *     whose access has not been withdrawn.
         */
        post: operations["setUserStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant a role
         * @description `ADMIN` only. Granting a role a user already holds is not an error.
         */
        post: operations["grantRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a role
         * @description `ADMIN` only. Revoking the last `ADMIN` role in a tenant is refused with
         *     `STATE_TRANSITION_INVALID`: a tenant with no administrator cannot be
         *     administered, and recovering from it is a support incident.
         */
        delete: operations["revokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tenant's sessions
         * @description `ADMIN` only. `current` marks the caller's own session, so an
         *     administrative screen can warn before revoking it rather than signing
         *     the administrator out with no explanation.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a session
         * @description `ADMIN` only. The session is marked revoked, never deleted.
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the tenant's audit trail
         * @description Readable by `ADMIN` and `AUDITOR`. Append-only: records are written, never
         *     amended, and a correction is a new record (ADR-0003).
         *
         *     `detail` is a canonical JSON document as a string. It is a string rather
         *     than an object because it is the exact bytes that were recorded and
         *     digested — re-encoding it through this API would mean the value a reader
         *     sees is this build's serializer's opinion of what was written, rather
         *     than what was written (ADR-0011 §2.7).
         */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Problem
         * @description RFC 9457 Problem Details, with the `ztx_` extensions from ADR-0016 §2.5.
         *     The extensions carry identifiers rather than data: an error that needs
         *     data to be understood names a decision or a request, and the data is
         *     fetched through an audited path.
         */
        Problem: {
            /**
             * Format: uri
             * @description A stable, versioned, documented URI for this reason code.
             * @example https://errors.zoikotax.com/v1/forbidden
             */
            type: string;
            /**
             * @description A short summary. **Do not match on this**; it may be reworded.
             * @example Forbidden
             */
            title: string;
            /**
             * Format: int32
             * @example 403
             */
            status: number;
            /** @description What happened and what to do about it. Also not for matching. */
            detail?: string;
            /**
             * @description The request path this occurred on.
             * @example /v1/admin/users
             */
            instance?: string;
            ztx_reason_code: components["schemas"]["ReasonCode"];
            /**
             * @description This request's identifier, also returned in the `X-Request-Id`
             *     header. Quote it in a support request; it is what correlates the
             *     response with the server-side log.
             * @example 01JBQ0S9C3X8Q1H6M2KX5R7F4H
             */
            ztx_request_id?: string;
            /** @description The OpenTelemetry trace identifier, where tracing is enabled. */
            ztx_trace_id?: string;
            /** @description The decision this error concerns, where there is one. */
            ztx_decision_id?: string;
            /**
             * @description The contract field at fault, for a validation failure. A field name,
             *     never a value — a value in an error message is a value in a log.
             * @example email
             */
            ztx_field?: string;
            /**
             * @description Whether retrying this request unchanged could succeed. Only a
             *     transient failure is retryable; everything else fails identically,
             *     and a client that retries a validation failure is generating load
             *     rather than making progress.
             * @example false
             */
            ztx_retryable: boolean;
        };
        /**
         * ReasonCode
         * @description A registered code from a closed vocabulary (ADR-0016 §2.4). Codes are
         *     never renumbered, never reused and never redefined; a retired code stops
         *     being emitted and keeps its meaning so historical evidence still
         *     resolves.
         *
         *     This is the field to branch on. The set this deployment can emit is
         *     reported by `GET /v1/capabilities`; the enum is deliberately not closed
         *     here, because the register grows by addition and a client that rejects
         *     an unrecognised code would break on an additive change (ADR-0010 §2.6).
         * @example FORBIDDEN
         */
        ReasonCode: string;
        /**
         * Timestamp
         * Format: date-time
         * @description RFC 3339 UTC with exactly six fractional digits and a literal `Z`
         *     (ADR-0011 §2.1 P2). No offsets and no variable precision, because two
         *     encodings of one instant must not produce two digests.
         * @example 2026-09-23T12:00:00.000000Z
         */
        Timestamp: string;
        /**
         * Digest
         * @description A canonical digest: SHA-256 over the canonical bytes, lowercase hex,
         *     carrying its profile-and-algorithm prefix (ADR-0011 §2.3). The prefix is
         *     not decoration — a future `zt2:` digest of the same document is a
         *     different digest, and comparing the two without it would be wrong.
         * @example zt1:be8651b55057f0f11f2a39820495b373417e5aa81b122f61b9fcb79faaf86c7b
         */
        Digest: string;
        /**
         * TenantId
         * @description A tenant identifier (ADR-0012). Prefixed, sortable, never recycled.
         * @example ztn_01JBQ0S9C3X8Q1H6M2KX5R7F4A
         */
        TenantId: string;
        /**
         * UserId
         * @description A user identifier (ADR-0012).
         * @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4B
         */
        UserId: string;
        /**
         * SessionId
         * @description A session identifier (ADR-0012). It is **not** the session secret: the
         *     secret is in the cookie, is never returned by this API, and is not
         *     derivable from this.
         * @example zts_01JBQ0S9C3X8Q1H6M2KX5R7F4E
         */
        SessionId: string;
        /**
         * AuditId
         * @description An audit record identifier (ADR-0012).
         * @example zta_01JBQ0S9C3X8Q1H6M2KX5R7F4G
         */
        AuditId: string;
        /**
         * Role
         * @description A role within a tenant. Closed: adding one is a reviewed change with an
         *     authorization matrix entry, not a string a caller may invent.
         * @example ADMIN
         * @enum {string}
         */
        Role: "ADMIN" | "OPERATOR" | "ANALYST" | "AUDITOR";
        /**
         * TenantStatus
         * @example ACTIVE
         * @enum {string}
         */
        TenantStatus: "ACTIVE" | "SUSPENDED" | "CLOSED";
        /**
         * UserStatus
         * @description `INVITED` is a user who exists and has no password, and therefore cannot
         *     sign in. It is a distinct state rather than a disabled user, because the
         *     two lead to different administrative actions.
         * @example ACTIVE
         * @enum {string}
         */
        UserStatus: "ACTIVE" | "INVITED" | "DISABLED";
        /** Tenant */
        Tenant: {
            id: components["schemas"]["TenantId"];
            /**
             * @description The stable, human-usable name a client signs in with.
             * @example acme
             */
            slug: string;
            /** @example Acme Telecom */
            displayName: string;
            /**
             * @description The region whose cell holds this tenant's data. It never leaves it,
             *     which is why this is reported rather than inferred.
             * @example eu-west
             */
            residencyRegion: string;
            status: components["schemas"]["TenantStatus"];
        };
        /**
         * User
         * @description A user as this API represents one. Note what is absent and always will
         *     be: there is no password, no verifier, no salt and no parameter set. A
         *     domain type serialized directly is a domain type whose every future
         *     field becomes public API by accident.
         */
        User: {
            id: components["schemas"]["UserId"];
            /**
             * Format: email
             * @example analyst@acme.example
             */
            email: string;
            /** @example Grace Hopper */
            displayName: string;
            status: components["schemas"]["UserStatus"];
            /** @description The roles this user holds, which may be empty. */
            roles: components["schemas"]["Role"][];
            createdAt: components["schemas"]["Timestamp"];
        };
        /**
         * Session
         * @description The current session. It carries no token: the session secret is in an
         *     `HttpOnly` cookie and is never in a response body.
         */
        Session: {
            tenant: components["schemas"]["Tenant"];
            user: components["schemas"]["User"];
            /**
             * @description The session's absolute expiry. Absolute, not idle: activity does not
             *     extend it, so a session ends at a time that was fixed when it began.
             */
            expiresAt: components["schemas"]["Timestamp"];
        };
        /** SessionSummary */
        SessionSummary: {
            id: components["schemas"]["SessionId"];
            userId: components["schemas"]["UserId"];
            createdAt: components["schemas"]["Timestamp"];
            expiresAt: components["schemas"]["Timestamp"];
            /** @description The user agent recorded when the session opened, where one was sent. */
            userAgent?: string;
            /** @description The client address recorded when the session opened. */
            clientIp?: string;
            /**
             * @description Whether the session has been revoked. A revoked session is kept
             *     rather than deleted; a session that vanished would leave nothing for
             *     an audit to look at.
             */
            revoked: boolean;
            /** @description Whether this is the calling session. */
            current: boolean;
        };
        /** AuditRecord */
        AuditRecord: {
            id: components["schemas"]["AuditId"];
            /**
             * @description Absent where the action had no human actor — a bootstrap at startup,
             *     or a scheduled sweep. Absent rather than a placeholder identifier,
             *     because "the system did this" and "some user did this" are different
             *     facts.
             */
            actorUserId?: components["schemas"]["UserId"];
            /**
             * @description A dotted action name from a closed vocabulary.
             * @example user.role.granted
             */
            action: string;
            /** @example user */
            subjectType: string;
            /** @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4C */
            subjectId: string;
            /**
             * @description A canonical JSON document, as a string. It is the exact bytes that
             *     were recorded and digested, so it is passed through rather than
             *     re-encoded (ADR-0011 §2.7).
             * @example {"role":"AUDITOR"}
             */
            detail: string;
            recordedAt: components["schemas"]["Timestamp"];
        };
        /** Capabilities */
        Capabilities: {
            /**
             * @description The cell serving this request.
             * @example eu-west-1
             */
            cell: string;
            /** @example eu-west */
            region: string;
            /** @example production */
            environment: string;
            trains: components["schemas"]["Trains"];
            /**
             * @description The canonicalization profile this deployment digests under. It is
             *     never redefined: a change to any profile rule is a new profile, and
             *     the old one stays implemented for as long as any record references
             *     it (ADR-0011 §2.6).
             * @example canon/v1
             */
            canonProfile: string;
            /**
             * @description **Whether this deployment may produce authoritative fiscal output.**
             *     False until A4. A deployment reporting `false` produces advisory
             *     figures that must not be filed, and says so here rather than leaving
             *     a client to assume.
             * @example false
             */
            authoritative: boolean;
            /** @description Every reason code this deployment can emit. */
            reasonCodes: components["schemas"]["ReasonCode"][];
            content?: components["schemas"]["ContentCapability"];
        };
        /**
         * Trains
         * @description The seven release-train versions. Together they name the exact
         *     combination of code, content, models, adapters, infrastructure, schemas
         *     and migrations that produced a response — which is what makes a decision
         *     replayable years later.
         */
        Trains: {
            /** @example 0.4.0 */
            app: string;
            /** @example 2026.09.1 */
            content: string;
            /** @example 0.1.0 */
            ai: string;
            /** @example 0.2.0 */
            adapter: string;
            /** @example 0.3.0 */
            infra: string;
            /** @example 0.1.0 */
            schema: string;
            /** @example 6 */
            migration: string;
        };
        /**
         * ContentCapability
         * @description The rule bundle this cell is running. Absent where no bundle is loaded.
         *
         *     The digest is here because it is what a replay names: quoting the bundle
         *     identifier alone would not distinguish two builds of one pack, and the
         *     difference between them is a difference in law.
         */
        ContentCapability: {
            /** @example eu-vat-worked-2026.09 */
            bundleId: string;
            digest: components["schemas"]["Digest"];
            /**
             * Format: int32
             * @description The rule-IR instruction-set version the bundle was compiled for. A
             *     runtime that cannot execute a bundle refuses to load it and stays on
             *     the previous one rather than degrading (ADR-0005 §2.8).
             * @example 1
             */
            irVersion: number;
            /**
             * Format: int32
             * @description The size of the rule graph, for telemetry.
             * @example 22
             */
            nodeCount: number;
        };
        /** SignInRequest */
        SignInRequest: {
            /**
             * @description The tenant slug.
             * @example acme
             */
            tenant: string;
            /**
             * Format: email
             * @example admin@acme.example
             */
            email: string;
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * Format: password
             * @example correct horse battery staple
             */
            currentPassword: string;
            /**
             * Format: password
             * @example a considerably longer passphrase than that one
             */
            newPassword: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /**
             * Format: email
             * @example auditor@acme.example
             */
            email: string;
            /** @example Katherine Johnson */
            displayName: string;
            /** @description Roles to grant on creation. A user may be created with none. */
            roles?: components["schemas"]["Role"][];
            /**
             * Format: password
             * @description Optional. Omitting it creates an `INVITED` user who cannot sign in
             *     until a password is set.
             */
            password?: string;
        };
        /** SetUserStatusRequest */
        SetUserStatusRequest: {
            status: components["schemas"]["UserStatus"];
        };
        /** RoleRequest */
        RoleRequest: {
            role: components["schemas"]["Role"];
        };
    };
    responses: {
        /** @description The request was malformed or violated the contract. */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid session, or a session that has expired or been revoked. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The subject is known and does not hold a role permitting this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The resource does not exist, or is outside the caller's tenant. The two
         *     are one answer on purpose: distinguishing them would tell a caller what
         *     exists in a tenant they cannot see.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A uniqueness violation, an optimistic conflict or a state-machine violation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description A defect. The cause is recorded and alerted; it is deliberately not in
         *     the response, because an error string from a driver carries table names,
         *     query fragments and values (ADR-0016 §2.6).
         */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description A transient failure. The request was not applied and may be retried
         *     unchanged — `ztx_retryable` is `true`, and `Retry-After` says when.
         */
        Unavailable: {
            headers: {
                /**
                 * @description Seconds to wait before retrying.
                 * @example 2
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Maximum number of items to return. The server caps this independently,
         *     so a larger value is not an error and does not return more.
         * @example 50
         */
        Limit: number;
        /**
         * @description The user identifier.
         * @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4C
         */
        UserId: components["schemas"]["UserId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deployment's effective capability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description The session, and the subject it belongs to. */
            200: {
                headers: {
                    /**
                     * @description The opaque session cookie. `__Host-ztax_session` where the
                     *     deployment is served over TLS; `ztax_session` on plain HTTP in
                     *     local development only, because a browser silently drops a
                     *     `__Host-` cookie that is not `Secure`.
                     * @example __Host-ztax_session=…; Path=/; Secure; HttpOnly; SameSite=Strict
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is revoked and the cookie is cleared. */
            204: {
                headers: {
                    /**
                     * @description The cleared session cookie.
                     * @example __Host-ztax_session=; Path=/; Max-Age=0; Secure; HttpOnly; SameSite=Strict
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password is changed and every session is revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of items to return. The server caps this independently,
                 *     so a larger value is not an error and does not return more.
                 * @example 50
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["User"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description The created user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The user identifier.
                 * @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4C
                 */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUserStatusRequest"];
            };
        };
        responses: {
            /** @description The status is set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    grantRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The user identifier.
                 * @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4C
                 */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description The role is granted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The user identifier.
                 * @example ztu_01JBQ0S9C3X8Q1H6M2KX5R7F4C
                 */
                userId: components["parameters"]["UserId"];
                /**
                 * @description The role to revoke.
                 * @example AUDITOR
                 */
                role: components["schemas"]["Role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role is revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of items to return. The server caps this independently,
                 *     so a larger value is not an error and does not return more.
                 * @example 50
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["SessionSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The session identifier.
                 * @example zts_01JBQ0S9C3X8Q1H6M2KX5R7F4F
                 */
                sessionId: components["schemas"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Validation"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of items to return. The server caps this independently,
                 *     so a larger value is not an error and does not return more.
                 * @example 50
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audit records, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        records: components["schemas"]["AuditRecord"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
}
